/* Generated by Yosys 0.9 (git sha1 1979e0b1, i686-w64-mingw32.static-g++ 5.5.0 -Os) */

(* top =  1  *)
(* src = "bending_machine_mk2.v:3" *)
module bending_mk2(clk, rst, ten, fif, change, serv);
  (* src = "bending_machine_mk2.v:12" *)
  wire [2:0] _00_;
  (* src = "bending_machine_mk2.v:12" *)
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  (* src = "bending_machine_mk2.v:12" *)
  wire _37_;
  (* src = "bending_machine_mk2.v:12" *)
  wire _38_;
  (* src = "bending_machine_mk2.v:12" *)
  wire _39_;
  (* src = "bending_machine_mk2.v:12" *)
  wire _40_;
  (* src = "bending_machine_mk2.v:9" *)
  wire _41_;
  (* src = "bending_machine_mk2.v:9" *)
  wire _42_;
  (* src = "bending_machine_mk2.v:3" *)
  wire _43_;
  (* src = "bending_machine_mk2.v:3" *)
  wire _44_;
  (* src = "bending_machine_mk2.v:3" *)
  wire _45_;
  wire _46_;
  wire _47_;
  wire _48_;
  wire _49_;
  wire _50_;
  wire _51_;
  wire _52_;
  wire _53_;
  wire _54_;
  wire _55_;
  wire _56_;
  wire _57_;
  wire _58_;
  wire _59_;
  wire _60_;
  (* src = "bending_machine_mk2.v:3" *)
  wire _61_;
  (* src = "bending_machine_mk2.v:3" *)
  wire _62_;
  (* src = "bending_machine_mk2.v:9" *)
  wire a;
  (* src = "bending_machine_mk2.v:9" *)
  wire b;
  (* src = "bending_machine_mk2.v:3" *)
  output [2:0] change;
  (* src = "bending_machine_mk2.v:3" *)
  input clk;
  (* src = "bending_machine_mk2.v:3" *)
  input fif;
  (* src = "bending_machine_mk2.v:3" *)
  input rst;
  (* src = "bending_machine_mk2.v:3" *)
  output serv;
  (* src = "bending_machine_mk2.v:3" *)
  input ten;
  INVX1 _63_ (
    .A(_45_),
    .Y(_46_)
  );
  INVX1 _64_ (
    .A(_44_),
    .Y(_47_)
  );
  INVX1 _65_ (
    .A(_61_),
    .Y(_48_)
  );
  INVX1 _66_ (
    .A(_62_),
    .Y(_49_)
  );
  NOR3X1 _67_ (
    .A(_41_),
    .B(_44_),
    .C(_43_),
    .Y(_50_)
  );
  NOR2X1 _68_ (
    .A(_41_),
    .B(_45_),
    .Y(_51_)
  );
  NOR2X1 _69_ (
    .A(_50_),
    .B(_51_),
    .Y(_52_)
  );
  AOI21X1 _70_ (
    .A(_49_),
    .B(_52_),
    .C(_61_),
    .Y(_40_)
  );
  AND2X1 _71_ (
    .A(_41_),
    .B(_43_),
    .Y(_53_)
  );
  NAND2X1 _72_ (
    .A(_41_),
    .B(_43_),
    .Y(_54_)
  );
  AOI21X1 _73_ (
    .A(_46_),
    .B(_43_),
    .C(_41_),
    .Y(_55_)
  );
  MUX2X1 _74_ (
    .A(_44_),
    .B(_54_),
    .S(_45_),
    .Y(_56_)
  );
  OAI21X1 _75_ (
    .A(_55_),
    .B(_56_),
    .C(_48_),
    .Y(_37_)
  );
  NAND3X1 _76_ (
    .A(_46_),
    .B(_47_),
    .C(_53_),
    .Y(_57_)
  );
  NAND2X1 _77_ (
    .A(_46_),
    .B(_44_),
    .Y(_58_)
  );
  NAND3X1 _78_ (
    .A(_46_),
    .B(_44_),
    .C(_54_),
    .Y(_59_)
  );
  AOI21X1 _79_ (
    .A(_57_),
    .B(_59_),
    .C(_61_),
    .Y(_38_)
  );
  AOI21X1 _80_ (
    .A(_45_),
    .B(_50_),
    .C(_61_),
    .Y(_60_)
  );
  OAI21X1 _81_ (
    .A(_54_),
    .B(_58_),
    .C(_60_),
    .Y(_39_)
  );
  (* src = "bending_machine_mk2.v:12" *)
  DFFPOSX1 _82_ (
    .CLK(clk),
    .D(_00_[0]),
    .Q(change[0])
  );
  (* src = "bending_machine_mk2.v:12" *)
  DFFPOSX1 _83_ (
    .CLK(clk),
    .D(_00_[1]),
    .Q(change[1])
  );
  (* src = "bending_machine_mk2.v:12" *)
  DFFPOSX1 _84_ (
    .CLK(clk),
    .D(_00_[2]),
    .Q(change[2])
  );
  (* src = "bending_machine_mk2.v:12" *)
  DFFPOSX1 _85_ (
    .CLK(clk),
    .D(_01_),
    .Q(serv)
  );
  (* src = "bending_machine_mk2.v:12" *)
  DFFPOSX1 _86_ (
    .CLK(clk),
    .D(ten),
    .Q(a)
  );
  (* src = "bending_machine_mk2.v:12" *)
  DFFPOSX1 _87_ (
    .CLK(clk),
    .D(fif),
    .Q(b)
  );
  assign _42_ = b;
  assign _41_ = a;
  assign _45_ = change[2];
  assign _44_ = change[1];
  assign _43_ = change[0];
  assign _61_ = rst;
  assign _01_ = _40_;
  assign _00_[0] = _37_;
  assign _00_[1] = _38_;
  assign _00_[2] = _39_;
  assign _62_ = serv;
endmodule
