/* Generated by Yosys 0.9 (git sha1 1979e0b1, i686-w64-mingw32.static-g++ 5.5.0 -Os) */

(* top =  1  *)
(* src = "mkreq.v:3" *)
module mkreq(clk, rst, pkto, reqi);
  (* src = "mkreq.v:9" *)
  wire [3:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  (* src = "mkreq.v:9" *)
  wire _10_;
  (* src = "mkreq.v:9" *)
  wire _11_;
  (* src = "mkreq.v:9" *)
  wire _12_;
  (* src = "mkreq.v:9" *)
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  (* src = "mkreq.v:4" *)
  wire _21_;
  (* src = "mkreq.v:4" *)
  wire _22_;
  (* src = "mkreq.v:4" *)
  wire _23_;
  (* src = "mkreq.v:4" *)
  wire _24_;
  (* src = "mkreq.v:3" *)
  wire _25_;
  (* src = "mkreq.v:3" *)
  input clk;
  (* src = "mkreq.v:4" *)
  input [9:0] pkto;
  (* src = "mkreq.v:5" *)
  output [3:0] reqi;
  (* src = "mkreq.v:3" *)
  input rst;
  INVX1 _26_ (
    .A(_23_),
    .Y(_14_)
  );
  INVX1 _27_ (
    .A(_25_),
    .Y(_15_)
  );
  INVX1 _28_ (
    .A(_21_),
    .Y(_16_)
  );
  OR2X1 _29_ (
    .A(_25_),
    .B(_22_),
    .Y(_17_)
  );
  NAND3X1 _30_ (
    .A(_24_),
    .B(_14_),
    .C(_16_),
    .Y(_18_)
  );
  NOR2X1 _31_ (
    .A(_17_),
    .B(_18_),
    .Y(_10_)
  );
  NAND3X1 _32_ (
    .A(_24_),
    .B(_14_),
    .C(_21_),
    .Y(_19_)
  );
  NOR2X1 _33_ (
    .A(_17_),
    .B(_19_),
    .Y(_11_)
  );
  NAND2X1 _34_ (
    .A(_15_),
    .B(_22_),
    .Y(_20_)
  );
  NOR2X1 _35_ (
    .A(_18_),
    .B(_20_),
    .Y(_12_)
  );
  NOR2X1 _36_ (
    .A(_19_),
    .B(_20_),
    .Y(_13_)
  );
  (* src = "mkreq.v:9" *)
  DFFPOSX1 _37_ (
    .CLK(clk),
    .D(_00_[0]),
    .Q(reqi[0])
  );
  (* src = "mkreq.v:9" *)
  DFFPOSX1 _38_ (
    .CLK(clk),
    .D(_00_[1]),
    .Q(reqi[1])
  );
  (* src = "mkreq.v:9" *)
  DFFPOSX1 _39_ (
    .CLK(clk),
    .D(_00_[2]),
    .Q(reqi[2])
  );
  (* src = "mkreq.v:9" *)
  DFFPOSX1 _40_ (
    .CLK(clk),
    .D(_00_[3]),
    .Q(reqi[3])
  );
  assign _24_ = pkto[9];
  assign _23_ = pkto[8];
  assign _25_ = rst;
  assign _00_[0] = _10_;
  assign _22_ = pkto[1];
  assign _21_ = pkto[0];
  assign _00_[1] = _11_;
  assign _00_[2] = _12_;
  assign _00_[3] = _13_;
endmodule
