/* Generated by Yosys 0.9 (git sha1 1979e0b1, i686-w64-mingw32.static-g++ 5.5.0 -Os) */

(* src = "fifo.v:5" *)
module fifo(clk, rst, re, we, pkti, empty, full, pkto);
  (* src = "fifo.v:15" *)
  wire [3:0] _0000_;
  (* src = "fifo.v:15" *)
  wire [3:0] _0001_;
  wire _0002_;
  wire _0003_;
  wire _0004_;
  wire _0005_;
  wire _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  wire _0430_;
  wire _0431_;
  wire _0432_;
  wire _0433_;
  wire _0434_;
  wire _0435_;
  wire _0436_;
  wire _0437_;
  wire _0438_;
  wire _0439_;
  wire _0440_;
  wire _0441_;
  wire _0442_;
  wire _0443_;
  wire _0444_;
  wire _0445_;
  wire _0446_;
  wire _0447_;
  wire _0448_;
  wire _0449_;
  wire _0450_;
  wire _0451_;
  wire _0452_;
  wire _0453_;
  wire _0454_;
  wire _0455_;
  wire _0456_;
  wire _0457_;
  wire _0458_;
  wire _0459_;
  wire _0460_;
  wire _0461_;
  wire _0462_;
  wire _0463_;
  wire _0464_;
  wire _0465_;
  wire _0466_;
  wire _0467_;
  wire _0468_;
  wire _0469_;
  wire _0470_;
  wire _0471_;
  wire _0472_;
  wire _0473_;
  wire _0474_;
  wire _0475_;
  wire _0476_;
  wire _0477_;
  wire _0478_;
  wire _0479_;
  wire _0480_;
  wire _0481_;
  wire _0482_;
  wire _0483_;
  wire _0484_;
  wire _0485_;
  wire _0486_;
  wire _0487_;
  wire _0488_;
  wire _0489_;
  wire _0490_;
  wire _0491_;
  wire _0492_;
  wire _0493_;
  wire _0494_;
  wire _0495_;
  wire _0496_;
  wire _0497_;
  wire _0498_;
  wire _0499_;
  wire _0500_;
  wire _0501_;
  wire _0502_;
  wire _0503_;
  wire _0504_;
  wire _0505_;
  wire _0506_;
  wire _0507_;
  wire _0508_;
  wire _0509_;
  wire _0510_;
  wire _0511_;
  wire _0512_;
  wire _0513_;
  wire _0514_;
  wire _0515_;
  wire _0516_;
  wire _0517_;
  wire _0518_;
  wire _0519_;
  wire _0520_;
  wire _0521_;
  wire _0522_;
  wire _0523_;
  wire _0524_;
  wire _0525_;
  wire _0526_;
  wire _0527_;
  wire _0528_;
  wire _0529_;
  wire _0530_;
  wire _0531_;
  wire _0532_;
  wire _0533_;
  wire _0534_;
  wire _0535_;
  wire _0536_;
  wire _0537_;
  wire _0538_;
  wire _0539_;
  wire _0540_;
  wire _0541_;
  wire _0542_;
  wire _0543_;
  wire _0544_;
  wire _0545_;
  wire _0546_;
  wire _0547_;
  wire _0548_;
  wire _0549_;
  wire _0550_;
  wire _0551_;
  wire _0552_;
  wire _0553_;
  wire _0554_;
  wire _0555_;
  wire _0556_;
  wire _0557_;
  wire _0558_;
  wire _0559_;
  wire _0560_;
  wire _0561_;
  wire _0562_;
  wire _0563_;
  wire _0564_;
  wire _0565_;
  wire _0566_;
  wire _0567_;
  wire _0568_;
  wire _0569_;
  wire _0570_;
  wire _0571_;
  wire _0572_;
  wire _0573_;
  wire _0574_;
  wire _0575_;
  wire _0576_;
  wire _0577_;
  wire _0578_;
  wire _0579_;
  wire _0580_;
  wire _0581_;
  wire _0582_;
  wire _0583_;
  wire _0584_;
  wire _0585_;
  wire _0586_;
  wire _0587_;
  wire _0588_;
  wire _0589_;
  wire _0590_;
  wire _0591_;
  wire _0592_;
  wire _0593_;
  wire _0594_;
  wire _0595_;
  wire _0596_;
  wire _0597_;
  wire _0598_;
  wire _0599_;
  wire _0600_;
  wire _0601_;
  wire _0602_;
  wire _0603_;
  wire _0604_;
  wire _0605_;
  wire _0606_;
  wire _0607_;
  wire _0608_;
  wire _0609_;
  wire _0610_;
  wire _0611_;
  wire _0612_;
  wire _0613_;
  wire _0614_;
  wire _0615_;
  wire _0616_;
  wire _0617_;
  wire _0618_;
  wire _0619_;
  wire _0620_;
  wire _0621_;
  wire _0622_;
  wire _0623_;
  wire _0624_;
  wire _0625_;
  wire _0626_;
  wire _0627_;
  wire _0628_;
  wire _0629_;
  wire _0630_;
  wire _0631_;
  wire _0632_;
  wire _0633_;
  wire _0634_;
  wire _0635_;
  wire _0636_;
  wire _0637_;
  wire _0638_;
  wire _0639_;
  wire _0640_;
  wire _0641_;
  wire _0642_;
  wire _0643_;
  wire _0644_;
  wire _0645_;
  wire _0646_;
  wire _0647_;
  wire _0648_;
  wire _0649_;
  wire _0650_;
  wire _0651_;
  wire _0652_;
  wire _0653_;
  wire _0654_;
  wire _0655_;
  wire _0656_;
  wire _0657_;
  wire _0658_;
  wire _0659_;
  wire _0660_;
  wire _0661_;
  wire _0662_;
  wire _0663_;
  wire _0664_;
  wire _0665_;
  wire _0666_;
  wire _0667_;
  wire _0668_;
  wire _0669_;
  wire _0670_;
  wire _0671_;
  wire _0672_;
  wire _0673_;
  wire _0674_;
  wire _0675_;
  wire _0676_;
  wire _0677_;
  wire _0678_;
  wire _0679_;
  wire _0680_;
  wire _0681_;
  wire _0682_;
  wire _0683_;
  wire _0684_;
  wire _0685_;
  wire _0686_;
  wire _0687_;
  wire _0688_;
  wire _0689_;
  wire _0690_;
  wire _0691_;
  wire _0692_;
  wire _0693_;
  wire _0694_;
  wire _0695_;
  wire _0696_;
  wire _0697_;
  wire _0698_;
  wire _0699_;
  wire _0700_;
  wire _0701_;
  wire _0702_;
  wire _0703_;
  wire _0704_;
  wire _0705_;
  wire _0706_;
  wire _0707_;
  wire _0708_;
  wire _0709_;
  wire _0710_;
  wire _0711_;
  wire _0712_;
  wire _0713_;
  wire _0714_;
  wire _0715_;
  wire _0716_;
  wire _0717_;
  wire _0718_;
  wire _0719_;
  wire _0720_;
  wire _0721_;
  wire _0722_;
  wire _0723_;
  wire _0724_;
  wire _0725_;
  wire _0726_;
  wire _0727_;
  wire _0728_;
  wire _0729_;
  wire _0730_;
  wire _0731_;
  wire _0732_;
  wire _0733_;
  wire _0734_;
  wire _0735_;
  wire _0736_;
  wire _0737_;
  wire _0738_;
  wire _0739_;
  wire _0740_;
  wire _0741_;
  wire _0742_;
  wire _0743_;
  wire _0744_;
  wire _0745_;
  wire _0746_;
  wire _0747_;
  wire _0748_;
  wire _0749_;
  wire _0750_;
  wire _0751_;
  wire _0752_;
  wire _0753_;
  wire _0754_;
  wire _0755_;
  wire _0756_;
  (* src = "fifo.v:5" *)
  input clk;
  (* src = "fifo.v:8" *)
  output empty;
  (* src = "fifo.v:8" *)
  output full;
  (* src = "fifo.v:12" *)
  reg [3:0] head;
  reg [9:0] \mem[0] ;
  reg [9:0] \mem[10] ;
  reg [9:0] \mem[11] ;
  reg [9:0] \mem[12] ;
  reg [9:0] \mem[13] ;
  reg [9:0] \mem[14] ;
  reg [9:0] \mem[15] ;
  reg [9:0] \mem[1] ;
  reg [9:0] \mem[2] ;
  reg [9:0] \mem[3] ;
  reg [9:0] \mem[4] ;
  reg [9:0] \mem[5] ;
  reg [9:0] \mem[6] ;
  reg [9:0] \mem[7] ;
  reg [9:0] \mem[8] ;
  reg [9:0] \mem[9] ;
  (* src = "fifo.v:7" *)
  input [9:0] pkti;
  (* src = "fifo.v:9" *)
  output [9:0] pkto;
  (* src = "fifo.v:6" *)
  input re;
  (* src = "fifo.v:5" *)
  input rst;
  (* src = "fifo.v:12" *)
  reg [3:0] tail;
  (* src = "fifo.v:6" *)
  input we;
  assign _0257_ = ~(head[0] ^ tail[0]);
  assign _0258_ = head[1] ^ tail[1];
  assign _0259_ = _0258_ | ~(_0257_);
  assign _0260_ = ~(tail[2] ^ head[2]);
  assign _0261_ = head[3] ^ tail[3];
  assign _0262_ = _0261_ | ~(_0260_);
  assign empty = ~(_0262_ | _0259_);
  assign _0263_ = head[0] ^ tail[0];
  assign _0264_ = ~(head[1] ^ head[0]);
  assign _0265_ = ~(_0264_ ^ tail[1]);
  assign _0266_ = _0265_ | ~(_0263_);
  assign _0267_ = ~tail[2];
  assign _0268_ = head[1] & head[0];
  assign _0269_ = ~(_0268_ ^ head[2]);
  assign _0270_ = ~(_0269_ ^ _0267_);
  assign _0271_ = ~head[2];
  assign _0272_ = _0268_ & ~(_0271_);
  assign _0273_ = ~(_0272_ ^ head[3]);
  assign _0274_ = ~(_0273_ ^ tail[3]);
  assign _0275_ = _0274_ | ~(_0270_);
  assign full = ~(_0275_ | _0266_);
  assign _0276_ = tail[0] ? \mem[1] [0] : \mem[0] [0];
  assign _0277_ = tail[0] ? \mem[3] [0] : \mem[2] [0];
  assign _0278_ = tail[1] ? _0277_ : _0276_;
  assign _0279_ = tail[0] ? \mem[5] [0] : \mem[4] [0];
  assign _0280_ = tail[0] ? \mem[7] [0] : \mem[6] [0];
  assign _0281_ = tail[1] ? _0280_ : _0279_;
  assign _0282_ = tail[2] ? _0281_ : _0278_;
  assign _0283_ = tail[0] ? \mem[9] [0] : \mem[8] [0];
  assign _0284_ = tail[0] ? \mem[11] [0] : \mem[10] [0];
  assign _0285_ = tail[1] ? _0284_ : _0283_;
  assign _0286_ = tail[0] ? \mem[13] [0] : \mem[12] [0];
  assign _0287_ = tail[0] ? \mem[15] [0] : \mem[14] [0];
  assign _0288_ = tail[1] ? _0287_ : _0286_;
  assign _0289_ = tail[2] ? _0288_ : _0285_;
  assign pkto[0] = tail[3] ? _0289_ : _0282_;
  assign _0290_ = tail[0] ? \mem[1] [1] : \mem[0] [1];
  assign _0291_ = tail[0] ? \mem[3] [1] : \mem[2] [1];
  assign _0292_ = tail[1] ? _0291_ : _0290_;
  assign _0293_ = tail[0] ? \mem[5] [1] : \mem[4] [1];
  assign _0294_ = tail[0] ? \mem[7] [1] : \mem[6] [1];
  assign _0295_ = tail[1] ? _0294_ : _0293_;
  assign _0296_ = tail[2] ? _0295_ : _0292_;
  assign _0297_ = tail[0] ? \mem[9] [1] : \mem[8] [1];
  assign _0298_ = tail[0] ? \mem[11] [1] : \mem[10] [1];
  assign _0299_ = tail[1] ? _0298_ : _0297_;
  assign _0300_ = tail[0] ? \mem[13] [1] : \mem[12] [1];
  assign _0301_ = tail[0] ? \mem[15] [1] : \mem[14] [1];
  assign _0302_ = tail[1] ? _0301_ : _0300_;
  assign _0303_ = tail[2] ? _0302_ : _0299_;
  assign pkto[1] = tail[3] ? _0303_ : _0296_;
  assign _0304_ = tail[0] ? \mem[1] [2] : \mem[0] [2];
  assign _0305_ = tail[0] ? \mem[3] [2] : \mem[2] [2];
  assign _0306_ = tail[1] ? _0305_ : _0304_;
  assign _0307_ = tail[0] ? \mem[5] [2] : \mem[4] [2];
  assign _0308_ = tail[0] ? \mem[7] [2] : \mem[6] [2];
  assign _0309_ = tail[1] ? _0308_ : _0307_;
  assign _0310_ = tail[2] ? _0309_ : _0306_;
  assign _0311_ = tail[0] ? \mem[9] [2] : \mem[8] [2];
  assign _0312_ = tail[0] ? \mem[11] [2] : \mem[10] [2];
  assign _0313_ = tail[1] ? _0312_ : _0311_;
  assign _0314_ = tail[0] ? \mem[13] [2] : \mem[12] [2];
  assign _0315_ = tail[0] ? \mem[15] [2] : \mem[14] [2];
  assign _0316_ = tail[1] ? _0315_ : _0314_;
  assign _0317_ = tail[2] ? _0316_ : _0313_;
  assign pkto[2] = tail[3] ? _0317_ : _0310_;
  assign _0318_ = tail[0] ? \mem[1] [3] : \mem[0] [3];
  assign _0319_ = tail[0] ? \mem[3] [3] : \mem[2] [3];
  assign _0320_ = tail[1] ? _0319_ : _0318_;
  assign _0321_ = tail[0] ? \mem[5] [3] : \mem[4] [3];
  assign _0322_ = tail[0] ? \mem[7] [3] : \mem[6] [3];
  assign _0323_ = tail[1] ? _0322_ : _0321_;
  assign _0324_ = tail[2] ? _0323_ : _0320_;
  assign _0325_ = tail[0] ? \mem[9] [3] : \mem[8] [3];
  assign _0326_ = tail[0] ? \mem[11] [3] : \mem[10] [3];
  assign _0327_ = tail[1] ? _0326_ : _0325_;
  assign _0328_ = tail[0] ? \mem[13] [3] : \mem[12] [3];
  assign _0329_ = tail[0] ? \mem[15] [3] : \mem[14] [3];
  assign _0330_ = tail[1] ? _0329_ : _0328_;
  assign _0331_ = tail[2] ? _0330_ : _0327_;
  assign pkto[3] = tail[3] ? _0331_ : _0324_;
  assign _0332_ = tail[0] ? \mem[1] [4] : \mem[0] [4];
  assign _0333_ = tail[0] ? \mem[3] [4] : \mem[2] [4];
  assign _0334_ = tail[1] ? _0333_ : _0332_;
  assign _0335_ = tail[0] ? \mem[5] [4] : \mem[4] [4];
  assign _0336_ = tail[0] ? \mem[7] [4] : \mem[6] [4];
  assign _0337_ = tail[1] ? _0336_ : _0335_;
  assign _0338_ = tail[2] ? _0337_ : _0334_;
  assign _0339_ = tail[0] ? \mem[9] [4] : \mem[8] [4];
  assign _0340_ = tail[0] ? \mem[11] [4] : \mem[10] [4];
  assign _0341_ = tail[1] ? _0340_ : _0339_;
  assign _0342_ = tail[0] ? \mem[13] [4] : \mem[12] [4];
  assign _0343_ = tail[0] ? \mem[15] [4] : \mem[14] [4];
  assign _0344_ = tail[1] ? _0343_ : _0342_;
  assign _0345_ = tail[2] ? _0344_ : _0341_;
  assign pkto[4] = tail[3] ? _0345_ : _0338_;
  assign _0346_ = tail[0] ? \mem[1] [5] : \mem[0] [5];
  assign _0347_ = tail[0] ? \mem[3] [5] : \mem[2] [5];
  assign _0348_ = tail[1] ? _0347_ : _0346_;
  assign _0349_ = tail[0] ? \mem[5] [5] : \mem[4] [5];
  assign _0350_ = tail[0] ? \mem[7] [5] : \mem[6] [5];
  assign _0351_ = tail[1] ? _0350_ : _0349_;
  assign _0352_ = tail[2] ? _0351_ : _0348_;
  assign _0353_ = tail[0] ? \mem[9] [5] : \mem[8] [5];
  assign _0354_ = tail[0] ? \mem[11] [5] : \mem[10] [5];
  assign _0355_ = tail[1] ? _0354_ : _0353_;
  assign _0356_ = tail[0] ? \mem[13] [5] : \mem[12] [5];
  assign _0357_ = tail[0] ? \mem[15] [5] : \mem[14] [5];
  assign _0358_ = tail[1] ? _0357_ : _0356_;
  assign _0359_ = tail[2] ? _0358_ : _0355_;
  assign pkto[5] = tail[3] ? _0359_ : _0352_;
  assign _0360_ = tail[0] ? \mem[1] [6] : \mem[0] [6];
  assign _0361_ = tail[0] ? \mem[3] [6] : \mem[2] [6];
  assign _0362_ = tail[1] ? _0361_ : _0360_;
  assign _0363_ = tail[0] ? \mem[5] [6] : \mem[4] [6];
  assign _0364_ = tail[0] ? \mem[7] [6] : \mem[6] [6];
  assign _0365_ = tail[1] ? _0364_ : _0363_;
  assign _0366_ = tail[2] ? _0365_ : _0362_;
  assign _0367_ = tail[0] ? \mem[9] [6] : \mem[8] [6];
  assign _0368_ = tail[0] ? \mem[11] [6] : \mem[10] [6];
  assign _0369_ = tail[1] ? _0368_ : _0367_;
  assign _0370_ = tail[0] ? \mem[13] [6] : \mem[12] [6];
  assign _0371_ = tail[0] ? \mem[15] [6] : \mem[14] [6];
  assign _0372_ = tail[1] ? _0371_ : _0370_;
  assign _0373_ = tail[2] ? _0372_ : _0369_;
  assign pkto[6] = tail[3] ? _0373_ : _0366_;
  assign _0374_ = tail[0] ? \mem[1] [7] : \mem[0] [7];
  assign _0375_ = tail[0] ? \mem[3] [7] : \mem[2] [7];
  assign _0376_ = tail[1] ? _0375_ : _0374_;
  assign _0377_ = tail[0] ? \mem[5] [7] : \mem[4] [7];
  assign _0378_ = tail[0] ? \mem[7] [7] : \mem[6] [7];
  assign _0379_ = tail[1] ? _0378_ : _0377_;
  assign _0380_ = tail[2] ? _0379_ : _0376_;
  assign _0381_ = tail[0] ? \mem[9] [7] : \mem[8] [7];
  assign _0382_ = tail[0] ? \mem[11] [7] : \mem[10] [7];
  assign _0383_ = tail[1] ? _0382_ : _0381_;
  assign _0384_ = tail[0] ? \mem[13] [7] : \mem[12] [7];
  assign _0385_ = tail[0] ? \mem[15] [7] : \mem[14] [7];
  assign _0386_ = tail[1] ? _0385_ : _0384_;
  assign _0387_ = tail[2] ? _0386_ : _0383_;
  assign pkto[7] = tail[3] ? _0387_ : _0380_;
  assign _0388_ = tail[0] ? \mem[1] [8] : \mem[0] [8];
  assign _0389_ = tail[0] ? \mem[3] [8] : \mem[2] [8];
  assign _0390_ = tail[1] ? _0389_ : _0388_;
  assign _0391_ = tail[0] ? \mem[5] [8] : \mem[4] [8];
  assign _0392_ = tail[0] ? \mem[7] [8] : \mem[6] [8];
  assign _0393_ = tail[1] ? _0392_ : _0391_;
  assign _0394_ = tail[2] ? _0393_ : _0390_;
  assign _0395_ = tail[0] ? \mem[9] [8] : \mem[8] [8];
  assign _0396_ = tail[0] ? \mem[11] [8] : \mem[10] [8];
  assign _0397_ = tail[1] ? _0396_ : _0395_;
  assign _0398_ = tail[0] ? \mem[13] [8] : \mem[12] [8];
  assign _0399_ = tail[0] ? \mem[15] [8] : \mem[14] [8];
  assign _0400_ = tail[1] ? _0399_ : _0398_;
  assign _0401_ = tail[2] ? _0400_ : _0397_;
  assign pkto[8] = tail[3] ? _0401_ : _0394_;
  assign _0402_ = tail[0] ? \mem[1] [9] : \mem[0] [9];
  assign _0403_ = tail[0] ? \mem[3] [9] : \mem[2] [9];
  assign _0404_ = tail[1] ? _0403_ : _0402_;
  assign _0405_ = tail[0] ? \mem[5] [9] : \mem[4] [9];
  assign _0406_ = tail[0] ? \mem[7] [9] : \mem[6] [9];
  assign _0407_ = tail[1] ? _0406_ : _0405_;
  assign _0408_ = tail[2] ? _0407_ : _0404_;
  assign _0409_ = tail[0] ? \mem[9] [9] : \mem[8] [9];
  assign _0410_ = tail[0] ? \mem[11] [9] : \mem[10] [9];
  assign _0411_ = tail[1] ? _0410_ : _0409_;
  assign _0412_ = tail[0] ? \mem[13] [9] : \mem[12] [9];
  assign _0413_ = tail[0] ? \mem[15] [9] : \mem[14] [9];
  assign _0414_ = tail[1] ? _0413_ : _0412_;
  assign _0415_ = tail[2] ? _0414_ : _0411_;
  assign pkto[9] = tail[3] ? _0415_ : _0408_;
  assign _0416_ = ~\mem[4] [0];
  assign _0417_ = rst | ~(we);
  assign _0418_ = head[0] & ~(_0417_);
  assign _0419_ = ~head[1];
  assign _0420_ = ~(_0417_ | _0419_);
  assign _0421_ = ~(_0420_ | _0418_);
  assign _0422_ = _0417_ | ~(head[2]);
  assign _0423_ = ~head[3];
  assign _0424_ = ~(_0417_ | _0423_);
  assign _0425_ = ~(_0424_ | _0422_);
  assign _0426_ = ~(_0425_ & _0421_);
  assign _0427_ = ~(rst | we);
  assign _0428_ = ~(_0427_ | _0426_);
  assign _0429_ = _0417_ | ~(pkti[0]);
  assign _0430_ = _0428_ ? _0429_ : _0416_;
  assign _0431_ = ~(_0272_ ^ _0423_);
  assign _0432_ = ~(_0431_ | _0269_);
  assign _0433_ = ~(_0432_ & _0268_);
  assign _0434_ = ~(_0433_ | _0417_);
  assign _0102_ = ~(_0434_ | _0430_);
  assign _0435_ = ~\mem[4] [1];
  assign _0436_ = _0417_ | ~(pkti[1]);
  assign _0437_ = _0428_ ? _0436_ : _0435_;
  assign _0103_ = ~(_0437_ | _0434_);
  assign _0438_ = ~\mem[4] [2];
  assign _0439_ = _0417_ | ~(pkti[2]);
  assign _0440_ = _0428_ ? _0439_ : _0438_;
  assign _0104_ = ~(_0440_ | _0434_);
  assign _0441_ = ~\mem[4] [3];
  assign _0442_ = _0417_ | ~(pkti[3]);
  assign _0443_ = _0428_ ? _0442_ : _0441_;
  assign _0105_ = ~(_0443_ | _0434_);
  assign _0444_ = ~\mem[4] [4];
  assign _0445_ = _0417_ | ~(pkti[4]);
  assign _0446_ = _0428_ ? _0445_ : _0444_;
  assign _0106_ = ~(_0446_ | _0434_);
  assign _0447_ = ~\mem[4] [5];
  assign _0448_ = _0417_ | ~(pkti[5]);
  assign _0449_ = _0428_ ? _0448_ : _0447_;
  assign _0107_ = ~(_0449_ | _0434_);
  assign _0450_ = ~\mem[4] [6];
  assign _0451_ = _0417_ | ~(pkti[6]);
  assign _0452_ = _0428_ ? _0451_ : _0450_;
  assign _0108_ = ~(_0452_ | _0434_);
  assign _0453_ = ~\mem[4] [7];
  assign _0454_ = _0417_ | ~(pkti[7]);
  assign _0455_ = _0428_ ? _0454_ : _0453_;
  assign _0109_ = ~(_0455_ | _0434_);
  assign _0456_ = ~\mem[4] [8];
  assign _0457_ = _0417_ | ~(pkti[8]);
  assign _0458_ = _0428_ ? _0457_ : _0456_;
  assign _0110_ = ~(_0458_ | _0434_);
  assign _0459_ = ~\mem[4] [9];
  assign _0460_ = _0417_ | ~(pkti[9]);
  assign _0461_ = _0428_ ? _0460_ : _0459_;
  assign _0111_ = ~(_0461_ | _0434_);
  assign _0462_ = ~\mem[5] [0];
  assign _0463_ = _0417_ | ~(head[0]);
  assign _0464_ = ~(_0420_ | _0463_);
  assign _0465_ = ~(_0464_ & _0425_);
  assign _0466_ = ~(_0465_ | _0427_);
  assign _0467_ = _0466_ ? _0429_ : _0462_;
  assign _0468_ = ~(head[1] | head[0]);
  assign _0469_ = ~(_0468_ & _0432_);
  assign _0470_ = ~(_0469_ | _0417_);
  assign _0112_ = ~(_0470_ | _0467_);
  assign _0471_ = ~\mem[5] [1];
  assign _0472_ = _0466_ ? _0436_ : _0471_;
  assign _0113_ = ~(_0472_ | _0470_);
  assign _0473_ = ~\mem[5] [2];
  assign _0474_ = _0466_ ? _0439_ : _0473_;
  assign _0114_ = ~(_0474_ | _0470_);
  assign _0475_ = ~\mem[5] [3];
  assign _0476_ = _0466_ ? _0442_ : _0475_;
  assign _0115_ = ~(_0476_ | _0470_);
  assign _0477_ = ~\mem[5] [4];
  assign _0478_ = _0466_ ? _0445_ : _0477_;
  assign _0116_ = ~(_0478_ | _0470_);
  assign _0479_ = ~\mem[5] [5];
  assign _0480_ = _0466_ ? _0448_ : _0479_;
  assign _0117_ = ~(_0480_ | _0470_);
  assign _0481_ = ~\mem[5] [6];
  assign _0482_ = _0466_ ? _0451_ : _0481_;
  assign _0118_ = ~(_0482_ | _0470_);
  assign _0483_ = ~\mem[5] [7];
  assign _0484_ = _0466_ ? _0454_ : _0483_;
  assign _0119_ = ~(_0484_ | _0470_);
  assign _0485_ = ~\mem[5] [8];
  assign _0486_ = _0466_ ? _0457_ : _0485_;
  assign _0120_ = ~(_0486_ | _0470_);
  assign _0487_ = ~\mem[5] [9];
  assign _0488_ = _0466_ ? _0460_ : _0487_;
  assign _0121_ = ~(_0488_ | _0470_);
  assign _0489_ = ~\mem[6] [0];
  assign _0490_ = _0417_ | ~(head[1]);
  assign _0491_ = ~(_0490_ | _0418_);
  assign _0492_ = ~(_0491_ & _0425_);
  assign _0493_ = ~(_0492_ | _0427_);
  assign _0494_ = _0493_ ? _0429_ : _0489_;
  assign _0495_ = head[0] & ~(head[1]);
  assign _0496_ = ~(_0495_ & _0432_);
  assign _0497_ = ~(_0496_ | _0417_);
  assign _0122_ = ~(_0497_ | _0494_);
  assign _0498_ = ~\mem[6] [1];
  assign _0499_ = _0493_ ? _0436_ : _0498_;
  assign _0123_ = ~(_0499_ | _0497_);
  assign _0500_ = ~\mem[6] [2];
  assign _0501_ = _0493_ ? _0439_ : _0500_;
  assign _0124_ = ~(_0501_ | _0497_);
  assign _0502_ = ~\mem[6] [3];
  assign _0503_ = _0493_ ? _0442_ : _0502_;
  assign _0125_ = ~(_0503_ | _0497_);
  assign _0504_ = ~\mem[6] [4];
  assign _0505_ = _0493_ ? _0445_ : _0504_;
  assign _0126_ = ~(_0505_ | _0497_);
  assign _0506_ = ~\mem[6] [5];
  assign _0507_ = _0493_ ? _0448_ : _0506_;
  assign _0127_ = ~(_0507_ | _0497_);
  assign _0508_ = ~\mem[6] [6];
  assign _0509_ = _0493_ ? _0451_ : _0508_;
  assign _0128_ = ~(_0509_ | _0497_);
  assign _0510_ = ~\mem[6] [7];
  assign _0511_ = _0493_ ? _0454_ : _0510_;
  assign _0129_ = ~(_0511_ | _0497_);
  assign _0512_ = ~\mem[6] [8];
  assign _0513_ = _0493_ ? _0457_ : _0512_;
  assign _0130_ = ~(_0513_ | _0497_);
  assign _0514_ = ~\mem[6] [9];
  assign _0515_ = _0493_ ? _0460_ : _0514_;
  assign _0131_ = ~(_0515_ | _0497_);
  assign _0516_ = ~\mem[7] [0];
  assign _0517_ = ~(_0490_ | _0463_);
  assign _0518_ = ~(_0517_ & _0425_);
  assign _0519_ = ~(_0518_ | _0427_);
  assign _0520_ = _0519_ ? _0429_ : _0516_;
  assign _0521_ = head[1] & ~(head[0]);
  assign _0522_ = ~(_0521_ & _0432_);
  assign _0523_ = ~(_0522_ | _0417_);
  assign _0132_ = ~(_0523_ | _0520_);
  assign _0524_ = ~\mem[7] [1];
  assign _0525_ = _0519_ ? _0436_ : _0524_;
  assign _0133_ = ~(_0525_ | _0523_);
  assign _0526_ = ~\mem[7] [2];
  assign _0527_ = _0519_ ? _0439_ : _0526_;
  assign _0134_ = ~(_0527_ | _0523_);
  assign _0528_ = ~\mem[7] [3];
  assign _0529_ = _0519_ ? _0442_ : _0528_;
  assign _0135_ = ~(_0529_ | _0523_);
  assign _0530_ = ~\mem[7] [4];
  assign _0531_ = _0519_ ? _0445_ : _0530_;
  assign _0136_ = ~(_0531_ | _0523_);
  assign _0532_ = ~\mem[7] [5];
  assign _0533_ = _0519_ ? _0448_ : _0532_;
  assign _0137_ = ~(_0533_ | _0523_);
  assign _0534_ = ~\mem[7] [6];
  assign _0535_ = _0519_ ? _0451_ : _0534_;
  assign _0138_ = ~(_0535_ | _0523_);
  assign _0536_ = ~\mem[7] [7];
  assign _0537_ = _0519_ ? _0454_ : _0536_;
  assign _0139_ = ~(_0537_ | _0523_);
  assign _0538_ = ~\mem[7] [8];
  assign _0539_ = _0519_ ? _0457_ : _0538_;
  assign _0140_ = ~(_0539_ | _0523_);
  assign _0540_ = ~\mem[7] [9];
  assign _0541_ = _0519_ ? _0460_ : _0540_;
  assign _0141_ = ~(_0541_ | _0523_);
  assign _0542_ = ~\mem[8] [0];
  assign _0543_ = _0417_ | ~(head[3]);
  assign _0544_ = _0543_ | ~(_0422_);
  assign _0545_ = _0544_ | ~(_0421_);
  assign _0546_ = ~(_0545_ | _0427_);
  assign _0547_ = _0546_ ? _0429_ : _0542_;
  assign _0548_ = _0273_ | ~(_0269_);
  assign _0549_ = _0548_ | ~(_0268_);
  assign _0550_ = ~(_0549_ | _0417_);
  assign _0142_ = ~(_0550_ | _0547_);
  assign _0551_ = ~\mem[8] [1];
  assign _0552_ = _0546_ ? _0436_ : _0551_;
  assign _0143_ = ~(_0552_ | _0550_);
  assign _0553_ = ~\mem[8] [2];
  assign _0554_ = _0546_ ? _0439_ : _0553_;
  assign _0144_ = ~(_0554_ | _0550_);
  assign _0555_ = ~\mem[8] [3];
  assign _0556_ = _0546_ ? _0442_ : _0555_;
  assign _0145_ = ~(_0556_ | _0550_);
  assign _0557_ = ~\mem[8] [4];
  assign _0558_ = _0546_ ? _0445_ : _0557_;
  assign _0146_ = ~(_0558_ | _0550_);
  assign _0559_ = ~\mem[8] [5];
  assign _0560_ = _0546_ ? _0448_ : _0559_;
  assign _0147_ = ~(_0560_ | _0550_);
  assign _0561_ = ~\mem[8] [6];
  assign _0562_ = _0546_ ? _0451_ : _0561_;
  assign _0148_ = ~(_0562_ | _0550_);
  assign _0563_ = ~\mem[8] [7];
  assign _0564_ = _0546_ ? _0454_ : _0563_;
  assign _0149_ = ~(_0564_ | _0550_);
  assign _0565_ = ~\mem[8] [8];
  assign _0566_ = _0546_ ? _0457_ : _0565_;
  assign _0150_ = ~(_0566_ | _0550_);
  assign _0567_ = ~\mem[8] [9];
  assign _0568_ = _0546_ ? _0460_ : _0567_;
  assign _0151_ = ~(_0568_ | _0550_);
  assign _0569_ = ~\mem[9] [0];
  assign _0570_ = _0544_ | ~(_0464_);
  assign _0571_ = ~(_0570_ | _0427_);
  assign _0572_ = _0571_ ? _0429_ : _0569_;
  assign _0573_ = _0548_ | ~(_0468_);
  assign _0574_ = ~(_0573_ | _0417_);
  assign _0152_ = ~(_0574_ | _0572_);
  assign _0575_ = ~\mem[9] [1];
  assign _0576_ = _0571_ ? _0436_ : _0575_;
  assign _0153_ = ~(_0576_ | _0574_);
  assign _0577_ = ~\mem[9] [2];
  assign _0578_ = _0571_ ? _0439_ : _0577_;
  assign _0154_ = ~(_0578_ | _0574_);
  assign _0579_ = ~\mem[9] [3];
  assign _0580_ = _0571_ ? _0442_ : _0579_;
  assign _0155_ = ~(_0580_ | _0574_);
  assign _0581_ = ~\mem[9] [4];
  assign _0582_ = _0571_ ? _0445_ : _0581_;
  assign _0156_ = ~(_0582_ | _0574_);
  assign _0583_ = ~\mem[9] [5];
  assign _0584_ = _0571_ ? _0448_ : _0583_;
  assign _0157_ = ~(_0584_ | _0574_);
  assign _0585_ = ~\mem[9] [6];
  assign _0586_ = _0571_ ? _0451_ : _0585_;
  assign _0158_ = ~(_0586_ | _0574_);
  assign _0587_ = ~\mem[9] [7];
  assign _0588_ = _0571_ ? _0454_ : _0587_;
  assign _0159_ = ~(_0588_ | _0574_);
  assign _0589_ = ~\mem[9] [8];
  assign _0590_ = _0571_ ? _0457_ : _0589_;
  assign _0160_ = ~(_0590_ | _0574_);
  assign _0591_ = ~\mem[9] [9];
  assign _0592_ = _0571_ ? _0460_ : _0591_;
  assign _0161_ = ~(_0592_ | _0574_);
  assign _0593_ = ~\mem[10] [0];
  assign _0594_ = _0544_ | ~(_0491_);
  assign _0595_ = ~(_0594_ | _0427_);
  assign _0596_ = _0595_ ? _0429_ : _0593_;
  assign _0597_ = _0548_ | ~(_0495_);
  assign _0598_ = ~(_0597_ | _0417_);
  assign _0012_ = ~(_0598_ | _0596_);
  assign _0599_ = ~\mem[10] [1];
  assign _0600_ = _0595_ ? _0436_ : _0599_;
  assign _0013_ = ~(_0600_ | _0598_);
  assign _0601_ = ~\mem[10] [2];
  assign _0602_ = _0595_ ? _0439_ : _0601_;
  assign _0014_ = ~(_0602_ | _0598_);
  assign _0603_ = ~\mem[10] [3];
  assign _0604_ = _0595_ ? _0442_ : _0603_;
  assign _0015_ = ~(_0604_ | _0598_);
  assign _0605_ = ~\mem[10] [4];
  assign _0606_ = _0595_ ? _0445_ : _0605_;
  assign _0016_ = ~(_0606_ | _0598_);
  assign _0607_ = ~\mem[10] [5];
  assign _0608_ = _0595_ ? _0448_ : _0607_;
  assign _0017_ = ~(_0608_ | _0598_);
  assign _0609_ = ~\mem[10] [6];
  assign _0610_ = _0595_ ? _0451_ : _0609_;
  assign _0018_ = ~(_0610_ | _0598_);
  assign _0611_ = ~\mem[10] [7];
  assign _0612_ = _0595_ ? _0454_ : _0611_;
  assign _0019_ = ~(_0612_ | _0598_);
  assign _0613_ = ~\mem[10] [8];
  assign _0614_ = _0595_ ? _0457_ : _0613_;
  assign _0020_ = ~(_0614_ | _0598_);
  assign _0615_ = ~\mem[10] [9];
  assign _0616_ = _0595_ ? _0460_ : _0615_;
  assign _0021_ = ~(_0616_ | _0598_);
  assign _0617_ = ~\mem[11] [0];
  assign _0618_ = _0544_ | ~(_0517_);
  assign _0619_ = ~(_0618_ | _0427_);
  assign _0620_ = _0619_ ? _0429_ : _0617_;
  assign _0621_ = _0548_ | ~(_0521_);
  assign _0622_ = ~(_0621_ | _0417_);
  assign _0022_ = ~(_0622_ | _0620_);
  assign _0623_ = ~\mem[11] [1];
  assign _0624_ = _0619_ ? _0436_ : _0623_;
  assign _0023_ = ~(_0624_ | _0622_);
  assign _0625_ = ~\mem[11] [2];
  assign _0626_ = _0619_ ? _0439_ : _0625_;
  assign _0024_ = ~(_0626_ | _0622_);
  assign _0627_ = ~\mem[11] [3];
  assign _0628_ = _0619_ ? _0442_ : _0627_;
  assign _0025_ = ~(_0628_ | _0622_);
  assign _0629_ = ~\mem[11] [4];
  assign _0630_ = _0619_ ? _0445_ : _0629_;
  assign _0026_ = ~(_0630_ | _0622_);
  assign _0631_ = ~\mem[11] [5];
  assign _0632_ = _0619_ ? _0448_ : _0631_;
  assign _0027_ = ~(_0632_ | _0622_);
  assign _0633_ = ~\mem[11] [6];
  assign _0634_ = _0619_ ? _0451_ : _0633_;
  assign _0028_ = ~(_0634_ | _0622_);
  assign _0635_ = ~\mem[11] [7];
  assign _0636_ = _0619_ ? _0454_ : _0635_;
  assign _0029_ = ~(_0636_ | _0622_);
  assign _0637_ = ~\mem[11] [8];
  assign _0638_ = _0619_ ? _0457_ : _0637_;
  assign _0030_ = ~(_0638_ | _0622_);
  assign _0639_ = ~\mem[11] [9];
  assign _0640_ = _0619_ ? _0460_ : _0639_;
  assign _0031_ = ~(_0640_ | _0622_);
  assign _0641_ = ~\mem[12] [0];
  assign _0642_ = _0543_ | _0422_;
  assign _0643_ = _0642_ | ~(_0421_);
  assign _0644_ = ~(_0643_ | _0427_);
  assign _0645_ = _0644_ ? _0429_ : _0641_;
  assign _0646_ = _0273_ | _0269_;
  assign _0647_ = _0646_ | ~(_0268_);
  assign _0648_ = ~(_0647_ | _0417_);
  assign _0032_ = ~(_0648_ | _0645_);
  assign _0649_ = ~\mem[12] [1];
  assign _0650_ = _0644_ ? _0436_ : _0649_;
  assign _0033_ = ~(_0650_ | _0648_);
  assign _0651_ = ~\mem[12] [2];
  assign _0652_ = _0644_ ? _0439_ : _0651_;
  assign _0034_ = ~(_0652_ | _0648_);
  assign _0653_ = ~\mem[12] [3];
  assign _0654_ = _0644_ ? _0442_ : _0653_;
  assign _0035_ = ~(_0654_ | _0648_);
  assign _0655_ = ~\mem[12] [4];
  assign _0656_ = _0644_ ? _0445_ : _0655_;
  assign _0036_ = ~(_0656_ | _0648_);
  assign _0657_ = ~\mem[12] [5];
  assign _0658_ = _0644_ ? _0448_ : _0657_;
  assign _0037_ = ~(_0658_ | _0648_);
  assign _0659_ = ~\mem[12] [6];
  assign _0660_ = _0644_ ? _0451_ : _0659_;
  assign _0038_ = ~(_0660_ | _0648_);
  assign _0661_ = ~\mem[12] [7];
  assign _0662_ = _0644_ ? _0454_ : _0661_;
  assign _0039_ = ~(_0662_ | _0648_);
  assign _0663_ = ~\mem[12] [8];
  assign _0664_ = _0644_ ? _0457_ : _0663_;
  assign _0040_ = ~(_0664_ | _0648_);
  assign _0665_ = ~\mem[12] [9];
  assign _0666_ = _0644_ ? _0460_ : _0665_;
  assign _0041_ = ~(_0666_ | _0648_);
  assign _0667_ = ~\mem[13] [0];
  assign _0668_ = _0642_ | ~(_0464_);
  assign _0669_ = ~(_0668_ | _0427_);
  assign _0670_ = _0669_ ? _0429_ : _0667_;
  assign _0671_ = _0646_ | ~(_0468_);
  assign _0672_ = ~(_0671_ | _0417_);
  assign _0042_ = ~(_0672_ | _0670_);
  assign _0673_ = ~\mem[13] [1];
  assign _0674_ = _0669_ ? _0436_ : _0673_;
  assign _0043_ = ~(_0674_ | _0672_);
  assign _0675_ = ~\mem[13] [2];
  assign _0676_ = _0669_ ? _0439_ : _0675_;
  assign _0044_ = ~(_0676_ | _0672_);
  assign _0677_ = ~\mem[13] [3];
  assign _0678_ = _0669_ ? _0442_ : _0677_;
  assign _0045_ = ~(_0678_ | _0672_);
  assign _0679_ = ~\mem[13] [4];
  assign _0680_ = _0669_ ? _0445_ : _0679_;
  assign _0046_ = ~(_0680_ | _0672_);
  assign _0681_ = ~\mem[13] [5];
  assign _0682_ = _0669_ ? _0448_ : _0681_;
  assign _0047_ = ~(_0682_ | _0672_);
  assign _0683_ = ~\mem[13] [6];
  assign _0684_ = _0669_ ? _0451_ : _0683_;
  assign _0048_ = ~(_0684_ | _0672_);
  assign _0685_ = ~\mem[13] [7];
  assign _0686_ = _0669_ ? _0454_ : _0685_;
  assign _0049_ = ~(_0686_ | _0672_);
  assign _0687_ = ~\mem[13] [8];
  assign _0688_ = _0669_ ? _0457_ : _0687_;
  assign _0050_ = ~(_0688_ | _0672_);
  assign _0689_ = ~\mem[13] [9];
  assign _0690_ = _0669_ ? _0460_ : _0689_;
  assign _0051_ = ~(_0690_ | _0672_);
  assign _0691_ = ~\mem[14] [0];
  assign _0692_ = _0642_ | ~(_0491_);
  assign _0693_ = ~(_0692_ | _0427_);
  assign _0694_ = _0693_ ? _0429_ : _0691_;
  assign _0695_ = _0646_ | ~(_0495_);
  assign _0696_ = ~(_0695_ | _0417_);
  assign _0052_ = ~(_0696_ | _0694_);
  assign _0697_ = ~\mem[14] [1];
  assign _0698_ = _0693_ ? _0436_ : _0697_;
  assign _0053_ = ~(_0698_ | _0696_);
  assign _0699_ = ~\mem[14] [2];
  assign _0700_ = _0693_ ? _0439_ : _0699_;
  assign _0054_ = ~(_0700_ | _0696_);
  assign _0701_ = ~\mem[14] [3];
  assign _0702_ = _0693_ ? _0442_ : _0701_;
  assign _0055_ = ~(_0702_ | _0696_);
  assign _0703_ = ~\mem[14] [4];
  assign _0704_ = _0693_ ? _0445_ : _0703_;
  assign _0056_ = ~(_0704_ | _0696_);
  assign _0705_ = ~\mem[14] [5];
  assign _0706_ = _0693_ ? _0448_ : _0705_;
  assign _0057_ = ~(_0706_ | _0696_);
  assign _0707_ = ~\mem[14] [6];
  assign _0708_ = _0693_ ? _0451_ : _0707_;
  assign _0058_ = ~(_0708_ | _0696_);
  assign _0709_ = ~\mem[14] [7];
  assign _0710_ = _0693_ ? _0454_ : _0709_;
  assign _0059_ = ~(_0710_ | _0696_);
  assign _0711_ = ~\mem[14] [8];
  assign _0712_ = _0693_ ? _0457_ : _0711_;
  assign _0060_ = ~(_0712_ | _0696_);
  assign _0713_ = ~\mem[14] [9];
  assign _0714_ = _0693_ ? _0460_ : _0713_;
  assign _0061_ = ~(_0714_ | _0696_);
  assign _0715_ = ~\mem[15] [0];
  assign _0716_ = _0642_ | ~(_0517_);
  assign _0717_ = ~(_0716_ | _0427_);
  assign _0718_ = _0717_ ? _0429_ : _0715_;
  assign _0719_ = _0646_ | ~(_0521_);
  assign _0720_ = ~(_0719_ | _0417_);
  assign _0062_ = ~(_0720_ | _0718_);
  assign _0721_ = ~\mem[15] [1];
  assign _0722_ = _0717_ ? _0436_ : _0721_;
  assign _0063_ = ~(_0722_ | _0720_);
  assign _0723_ = ~\mem[15] [2];
  assign _0724_ = _0717_ ? _0439_ : _0723_;
  assign _0064_ = ~(_0724_ | _0720_);
  assign _0725_ = ~\mem[15] [3];
  assign _0726_ = _0717_ ? _0442_ : _0725_;
  assign _0065_ = ~(_0726_ | _0720_);
  assign _0727_ = ~\mem[15] [4];
  assign _0728_ = _0717_ ? _0445_ : _0727_;
  assign _0066_ = ~(_0728_ | _0720_);
  assign _0729_ = ~\mem[15] [5];
  assign _0730_ = _0717_ ? _0448_ : _0729_;
  assign _0067_ = ~(_0730_ | _0720_);
  assign _0731_ = ~\mem[15] [6];
  assign _0732_ = _0717_ ? _0451_ : _0731_;
  assign _0068_ = ~(_0732_ | _0720_);
  assign _0733_ = ~\mem[15] [7];
  assign _0734_ = _0717_ ? _0454_ : _0733_;
  assign _0069_ = ~(_0734_ | _0720_);
  assign _0735_ = ~\mem[15] [8];
  assign _0736_ = _0717_ ? _0457_ : _0735_;
  assign _0070_ = ~(_0736_ | _0720_);
  assign _0737_ = ~\mem[15] [9];
  assign _0738_ = _0717_ ? _0460_ : _0737_;
  assign _0071_ = ~(_0738_ | _0720_);
  assign _0739_ = ~\mem[3] [0];
  assign _0740_ = _0424_ | ~(_0422_);
  assign _0741_ = _0740_ | ~(_0517_);
  assign _0742_ = ~(_0741_ | _0427_);
  assign _0743_ = _0742_ ? _0429_ : _0739_;
  assign _0744_ = _0431_ | ~(_0269_);
  assign _0745_ = _0744_ | ~(_0521_);
  assign _0746_ = ~(_0745_ | _0417_);
  assign _0092_ = ~(_0746_ | _0743_);
  assign _0747_ = ~\mem[3] [1];
  assign _0748_ = _0742_ ? _0436_ : _0747_;
  assign _0093_ = ~(_0748_ | _0746_);
  assign _0749_ = ~\mem[3] [2];
  assign _0750_ = _0742_ ? _0439_ : _0749_;
  assign _0094_ = ~(_0750_ | _0746_);
  assign _0751_ = ~\mem[3] [3];
  assign _0752_ = _0742_ ? _0442_ : _0751_;
  assign _0095_ = ~(_0752_ | _0746_);
  assign _0753_ = ~\mem[3] [4];
  assign _0754_ = _0742_ ? _0445_ : _0753_;
  assign _0096_ = ~(_0754_ | _0746_);
  assign _0755_ = ~\mem[3] [5];
  assign _0756_ = _0742_ ? _0448_ : _0755_;
  assign _0097_ = ~(_0756_ | _0746_);
  assign _0162_ = ~\mem[3] [6];
  assign _0163_ = _0742_ ? _0451_ : _0162_;
  assign _0098_ = ~(_0163_ | _0746_);
  assign _0164_ = ~\mem[3] [7];
  assign _0165_ = _0742_ ? _0454_ : _0164_;
  assign _0099_ = ~(_0165_ | _0746_);
  assign _0166_ = ~\mem[3] [8];
  assign _0167_ = _0742_ ? _0457_ : _0166_;
  assign _0100_ = ~(_0167_ | _0746_);
  assign _0168_ = ~\mem[3] [9];
  assign _0169_ = _0742_ ? _0460_ : _0168_;
  assign _0101_ = ~(_0169_ | _0746_);
  assign _0170_ = ~\mem[2] [0];
  assign _0171_ = _0740_ | ~(_0491_);
  assign _0172_ = ~(_0171_ | _0427_);
  assign _0173_ = _0172_ ? _0429_ : _0170_;
  assign _0174_ = _0744_ | ~(_0495_);
  assign _0175_ = ~(_0174_ | _0417_);
  assign _0082_ = ~(_0175_ | _0173_);
  assign _0176_ = ~\mem[2] [1];
  assign _0177_ = _0172_ ? _0436_ : _0176_;
  assign _0083_ = ~(_0177_ | _0175_);
  assign _0178_ = ~\mem[2] [2];
  assign _0179_ = _0172_ ? _0439_ : _0178_;
  assign _0084_ = ~(_0179_ | _0175_);
  assign _0180_ = ~\mem[2] [3];
  assign _0181_ = _0172_ ? _0442_ : _0180_;
  assign _0085_ = ~(_0181_ | _0175_);
  assign _0182_ = ~\mem[2] [4];
  assign _0183_ = _0172_ ? _0445_ : _0182_;
  assign _0086_ = ~(_0183_ | _0175_);
  assign _0184_ = ~\mem[2] [5];
  assign _0185_ = _0172_ ? _0448_ : _0184_;
  assign _0087_ = ~(_0185_ | _0175_);
  assign _0186_ = ~\mem[2] [6];
  assign _0187_ = _0172_ ? _0451_ : _0186_;
  assign _0088_ = ~(_0187_ | _0175_);
  assign _0188_ = ~\mem[2] [7];
  assign _0189_ = _0172_ ? _0454_ : _0188_;
  assign _0089_ = ~(_0189_ | _0175_);
  assign _0190_ = ~\mem[2] [8];
  assign _0191_ = _0172_ ? _0457_ : _0190_;
  assign _0090_ = ~(_0191_ | _0175_);
  assign _0192_ = ~\mem[2] [9];
  assign _0193_ = _0172_ ? _0460_ : _0192_;
  assign _0091_ = ~(_0193_ | _0175_);
  assign _0194_ = ~\mem[1] [0];
  assign _0195_ = _0740_ | ~(_0464_);
  assign _0196_ = ~(_0195_ | _0427_);
  assign _0197_ = _0196_ ? _0429_ : _0194_;
  assign _0198_ = _0744_ | ~(_0468_);
  assign _0199_ = ~(_0198_ | _0417_);
  assign _0072_ = ~(_0199_ | _0197_);
  assign _0200_ = ~\mem[1] [1];
  assign _0201_ = _0196_ ? _0436_ : _0200_;
  assign _0073_ = ~(_0201_ | _0199_);
  assign _0202_ = ~\mem[1] [2];
  assign _0203_ = _0196_ ? _0439_ : _0202_;
  assign _0074_ = ~(_0203_ | _0199_);
  assign _0204_ = ~\mem[1] [3];
  assign _0205_ = _0196_ ? _0442_ : _0204_;
  assign _0075_ = ~(_0205_ | _0199_);
  assign _0206_ = ~\mem[1] [4];
  assign _0207_ = _0196_ ? _0445_ : _0206_;
  assign _0076_ = ~(_0207_ | _0199_);
  assign _0208_ = ~\mem[1] [5];
  assign _0209_ = _0196_ ? _0448_ : _0208_;
  assign _0077_ = ~(_0209_ | _0199_);
  assign _0210_ = ~\mem[1] [6];
  assign _0211_ = _0196_ ? _0451_ : _0210_;
  assign _0078_ = ~(_0211_ | _0199_);
  assign _0212_ = ~\mem[1] [7];
  assign _0213_ = _0196_ ? _0454_ : _0212_;
  assign _0079_ = ~(_0213_ | _0199_);
  assign _0214_ = ~\mem[1] [8];
  assign _0215_ = _0196_ ? _0457_ : _0214_;
  assign _0080_ = ~(_0215_ | _0199_);
  assign _0216_ = ~\mem[1] [9];
  assign _0217_ = _0196_ ? _0460_ : _0216_;
  assign _0081_ = ~(_0217_ | _0199_);
  assign _0218_ = ~(re ^ tail[0]);
  assign _0001_[0] = ~(_0218_ | rst);
  assign _0219_ = ~tail[1];
  assign _0220_ = ~(tail[0] ^ tail[1]);
  assign _0221_ = re ? _0220_ : _0219_;
  assign _0001_[1] = ~(_0221_ | rst);
  assign _0222_ = ~(tail[0] & tail[1]);
  assign _0223_ = ~(_0222_ ^ _0267_);
  assign _0224_ = re ? _0223_ : _0267_;
  assign _0001_[2] = ~(_0224_ | rst);
  assign _0225_ = ~tail[3];
  assign _0226_ = ~(_0222_ | _0267_);
  assign _0227_ = ~(_0226_ ^ tail[3]);
  assign _0228_ = re ? _0227_ : _0225_;
  assign _0001_[3] = ~(_0228_ | rst);
  assign _0229_ = ~(we ^ head[0]);
  assign _0000_[0] = ~(_0229_ | rst);
  assign _0230_ = we ? _0264_ : _0419_;
  assign _0000_[1] = ~(_0230_ | rst);
  assign _0231_ = we ? _0269_ : _0271_;
  assign _0000_[2] = ~(_0231_ | rst);
  assign _0232_ = we ? _0273_ : _0423_;
  assign _0000_[3] = ~(_0232_ | rst);
  assign _0233_ = ~\mem[0] [0];
  assign _0234_ = _0740_ | ~(_0421_);
  assign _0235_ = ~(_0234_ | _0427_);
  assign _0236_ = _0235_ ? _0429_ : _0233_;
  assign _0237_ = _0268_ & ~(_0744_);
  assign _0238_ = _0237_ & ~(_0417_);
  assign _0002_ = ~(_0238_ | _0236_);
  assign _0239_ = ~\mem[0] [1];
  assign _0240_ = _0235_ ? _0436_ : _0239_;
  assign _0003_ = ~(_0240_ | _0238_);
  assign _0241_ = ~\mem[0] [2];
  assign _0242_ = _0235_ ? _0439_ : _0241_;
  assign _0004_ = ~(_0242_ | _0238_);
  assign _0243_ = ~\mem[0] [3];
  assign _0244_ = _0235_ ? _0442_ : _0243_;
  assign _0005_ = ~(_0244_ | _0238_);
  assign _0245_ = ~\mem[0] [4];
  assign _0246_ = _0235_ ? _0445_ : _0245_;
  assign _0006_ = ~(_0246_ | _0238_);
  assign _0247_ = ~\mem[0] [5];
  assign _0248_ = _0235_ ? _0448_ : _0247_;
  assign _0007_ = ~(_0248_ | _0238_);
  assign _0249_ = ~\mem[0] [6];
  assign _0250_ = _0235_ ? _0451_ : _0249_;
  assign _0008_ = ~(_0250_ | _0238_);
  assign _0251_ = ~\mem[0] [7];
  assign _0252_ = _0235_ ? _0454_ : _0251_;
  assign _0009_ = ~(_0252_ | _0238_);
  assign _0253_ = ~\mem[0] [8];
  assign _0254_ = _0235_ ? _0457_ : _0253_;
  assign _0010_ = ~(_0254_ | _0238_);
  assign _0255_ = ~\mem[0] [9];
  assign _0256_ = _0235_ ? _0460_ : _0255_;
  assign _0011_ = ~(_0256_ | _0238_);
  always @(posedge clk)
      \mem[14] [0] <= _0052_;
  always @(posedge clk)
      \mem[14] [1] <= _0053_;
  always @(posedge clk)
      \mem[14] [2] <= _0054_;
  always @(posedge clk)
      \mem[14] [3] <= _0055_;
  always @(posedge clk)
      \mem[14] [4] <= _0056_;
  always @(posedge clk)
      \mem[14] [5] <= _0057_;
  always @(posedge clk)
      \mem[14] [6] <= _0058_;
  always @(posedge clk)
      \mem[14] [7] <= _0059_;
  always @(posedge clk)
      \mem[14] [8] <= _0060_;
  always @(posedge clk)
      \mem[14] [9] <= _0061_;
  always @(posedge clk)
      \mem[15] [0] <= _0062_;
  always @(posedge clk)
      \mem[15] [1] <= _0063_;
  always @(posedge clk)
      \mem[15] [2] <= _0064_;
  always @(posedge clk)
      \mem[15] [3] <= _0065_;
  always @(posedge clk)
      \mem[15] [4] <= _0066_;
  always @(posedge clk)
      \mem[15] [5] <= _0067_;
  always @(posedge clk)
      \mem[15] [6] <= _0068_;
  always @(posedge clk)
      \mem[15] [7] <= _0069_;
  always @(posedge clk)
      \mem[15] [8] <= _0070_;
  always @(posedge clk)
      \mem[15] [9] <= _0071_;
  always @(posedge clk)
      tail[0] <= _0001_[0];
  always @(posedge clk)
      tail[1] <= _0001_[1];
  always @(posedge clk)
      tail[2] <= _0001_[2];
  always @(posedge clk)
      tail[3] <= _0001_[3];
  always @(posedge clk)
      \mem[2] [0] <= _0082_;
  always @(posedge clk)
      \mem[2] [1] <= _0083_;
  always @(posedge clk)
      \mem[2] [2] <= _0084_;
  always @(posedge clk)
      \mem[2] [3] <= _0085_;
  always @(posedge clk)
      \mem[2] [4] <= _0086_;
  always @(posedge clk)
      \mem[2] [5] <= _0087_;
  always @(posedge clk)
      \mem[2] [6] <= _0088_;
  always @(posedge clk)
      \mem[2] [7] <= _0089_;
  always @(posedge clk)
      \mem[2] [8] <= _0090_;
  always @(posedge clk)
      \mem[2] [9] <= _0091_;
  always @(posedge clk)
      \mem[1] [0] <= _0072_;
  always @(posedge clk)
      \mem[1] [1] <= _0073_;
  always @(posedge clk)
      \mem[1] [2] <= _0074_;
  always @(posedge clk)
      \mem[1] [3] <= _0075_;
  always @(posedge clk)
      \mem[1] [4] <= _0076_;
  always @(posedge clk)
      \mem[1] [5] <= _0077_;
  always @(posedge clk)
      \mem[1] [6] <= _0078_;
  always @(posedge clk)
      \mem[1] [7] <= _0079_;
  always @(posedge clk)
      \mem[1] [8] <= _0080_;
  always @(posedge clk)
      \mem[1] [9] <= _0081_;
  (* src = "fifo.v:15" *)
  always @(posedge clk)
      head[0] <= _0000_[0];
  (* src = "fifo.v:15" *)
  always @(posedge clk)
      head[1] <= _0000_[1];
  (* src = "fifo.v:15" *)
  always @(posedge clk)
      head[2] <= _0000_[2];
  (* src = "fifo.v:15" *)
  always @(posedge clk)
      head[3] <= _0000_[3];
  always @(posedge clk)
      \mem[7] [0] <= _0132_;
  always @(posedge clk)
      \mem[7] [1] <= _0133_;
  always @(posedge clk)
      \mem[7] [2] <= _0134_;
  always @(posedge clk)
      \mem[7] [3] <= _0135_;
  always @(posedge clk)
      \mem[7] [4] <= _0136_;
  always @(posedge clk)
      \mem[7] [5] <= _0137_;
  always @(posedge clk)
      \mem[7] [6] <= _0138_;
  always @(posedge clk)
      \mem[7] [7] <= _0139_;
  always @(posedge clk)
      \mem[7] [8] <= _0140_;
  always @(posedge clk)
      \mem[7] [9] <= _0141_;
  always @(posedge clk)
      \mem[10] [0] <= _0012_;
  always @(posedge clk)
      \mem[10] [1] <= _0013_;
  always @(posedge clk)
      \mem[10] [2] <= _0014_;
  always @(posedge clk)
      \mem[10] [3] <= _0015_;
  always @(posedge clk)
      \mem[10] [4] <= _0016_;
  always @(posedge clk)
      \mem[10] [5] <= _0017_;
  always @(posedge clk)
      \mem[10] [6] <= _0018_;
  always @(posedge clk)
      \mem[10] [7] <= _0019_;
  always @(posedge clk)
      \mem[10] [8] <= _0020_;
  always @(posedge clk)
      \mem[10] [9] <= _0021_;
  always @(posedge clk)
      \mem[6] [0] <= _0122_;
  always @(posedge clk)
      \mem[6] [1] <= _0123_;
  always @(posedge clk)
      \mem[6] [2] <= _0124_;
  always @(posedge clk)
      \mem[6] [3] <= _0125_;
  always @(posedge clk)
      \mem[6] [4] <= _0126_;
  always @(posedge clk)
      \mem[6] [5] <= _0127_;
  always @(posedge clk)
      \mem[6] [6] <= _0128_;
  always @(posedge clk)
      \mem[6] [7] <= _0129_;
  always @(posedge clk)
      \mem[6] [8] <= _0130_;
  always @(posedge clk)
      \mem[6] [9] <= _0131_;
  always @(posedge clk)
      \mem[3] [0] <= _0092_;
  always @(posedge clk)
      \mem[3] [1] <= _0093_;
  always @(posedge clk)
      \mem[3] [2] <= _0094_;
  always @(posedge clk)
      \mem[3] [3] <= _0095_;
  always @(posedge clk)
      \mem[3] [4] <= _0096_;
  always @(posedge clk)
      \mem[3] [5] <= _0097_;
  always @(posedge clk)
      \mem[3] [6] <= _0098_;
  always @(posedge clk)
      \mem[3] [7] <= _0099_;
  always @(posedge clk)
      \mem[3] [8] <= _0100_;
  always @(posedge clk)
      \mem[3] [9] <= _0101_;
  always @(posedge clk)
      \mem[0] [0] <= _0002_;
  always @(posedge clk)
      \mem[0] [1] <= _0003_;
  always @(posedge clk)
      \mem[0] [2] <= _0004_;
  always @(posedge clk)
      \mem[0] [3] <= _0005_;
  always @(posedge clk)
      \mem[0] [4] <= _0006_;
  always @(posedge clk)
      \mem[0] [5] <= _0007_;
  always @(posedge clk)
      \mem[0] [6] <= _0008_;
  always @(posedge clk)
      \mem[0] [7] <= _0009_;
  always @(posedge clk)
      \mem[0] [8] <= _0010_;
  always @(posedge clk)
      \mem[0] [9] <= _0011_;
  always @(posedge clk)
      \mem[5] [0] <= _0112_;
  always @(posedge clk)
      \mem[5] [1] <= _0113_;
  always @(posedge clk)
      \mem[5] [2] <= _0114_;
  always @(posedge clk)
      \mem[5] [3] <= _0115_;
  always @(posedge clk)
      \mem[5] [4] <= _0116_;
  always @(posedge clk)
      \mem[5] [5] <= _0117_;
  always @(posedge clk)
      \mem[5] [6] <= _0118_;
  always @(posedge clk)
      \mem[5] [7] <= _0119_;
  always @(posedge clk)
      \mem[5] [8] <= _0120_;
  always @(posedge clk)
      \mem[5] [9] <= _0121_;
  always @(posedge clk)
      \mem[11] [0] <= _0022_;
  always @(posedge clk)
      \mem[11] [1] <= _0023_;
  always @(posedge clk)
      \mem[11] [2] <= _0024_;
  always @(posedge clk)
      \mem[11] [3] <= _0025_;
  always @(posedge clk)
      \mem[11] [4] <= _0026_;
  always @(posedge clk)
      \mem[11] [5] <= _0027_;
  always @(posedge clk)
      \mem[11] [6] <= _0028_;
  always @(posedge clk)
      \mem[11] [7] <= _0029_;
  always @(posedge clk)
      \mem[11] [8] <= _0030_;
  always @(posedge clk)
      \mem[11] [9] <= _0031_;
  always @(posedge clk)
      \mem[8] [0] <= _0142_;
  always @(posedge clk)
      \mem[8] [1] <= _0143_;
  always @(posedge clk)
      \mem[8] [2] <= _0144_;
  always @(posedge clk)
      \mem[8] [3] <= _0145_;
  always @(posedge clk)
      \mem[8] [4] <= _0146_;
  always @(posedge clk)
      \mem[8] [5] <= _0147_;
  always @(posedge clk)
      \mem[8] [6] <= _0148_;
  always @(posedge clk)
      \mem[8] [7] <= _0149_;
  always @(posedge clk)
      \mem[8] [8] <= _0150_;
  always @(posedge clk)
      \mem[8] [9] <= _0151_;
  always @(posedge clk)
      \mem[9] [0] <= _0152_;
  always @(posedge clk)
      \mem[9] [1] <= _0153_;
  always @(posedge clk)
      \mem[9] [2] <= _0154_;
  always @(posedge clk)
      \mem[9] [3] <= _0155_;
  always @(posedge clk)
      \mem[9] [4] <= _0156_;
  always @(posedge clk)
      \mem[9] [5] <= _0157_;
  always @(posedge clk)
      \mem[9] [6] <= _0158_;
  always @(posedge clk)
      \mem[9] [7] <= _0159_;
  always @(posedge clk)
      \mem[9] [8] <= _0160_;
  always @(posedge clk)
      \mem[9] [9] <= _0161_;
  always @(posedge clk)
      \mem[4] [0] <= _0102_;
  always @(posedge clk)
      \mem[4] [1] <= _0103_;
  always @(posedge clk)
      \mem[4] [2] <= _0104_;
  always @(posedge clk)
      \mem[4] [3] <= _0105_;
  always @(posedge clk)
      \mem[4] [4] <= _0106_;
  always @(posedge clk)
      \mem[4] [5] <= _0107_;
  always @(posedge clk)
      \mem[4] [6] <= _0108_;
  always @(posedge clk)
      \mem[4] [7] <= _0109_;
  always @(posedge clk)
      \mem[4] [8] <= _0110_;
  always @(posedge clk)
      \mem[4] [9] <= _0111_;
  always @(posedge clk)
      \mem[12] [0] <= _0032_;
  always @(posedge clk)
      \mem[12] [1] <= _0033_;
  always @(posedge clk)
      \mem[12] [2] <= _0034_;
  always @(posedge clk)
      \mem[12] [3] <= _0035_;
  always @(posedge clk)
      \mem[12] [4] <= _0036_;
  always @(posedge clk)
      \mem[12] [5] <= _0037_;
  always @(posedge clk)
      \mem[12] [6] <= _0038_;
  always @(posedge clk)
      \mem[12] [7] <= _0039_;
  always @(posedge clk)
      \mem[12] [8] <= _0040_;
  always @(posedge clk)
      \mem[12] [9] <= _0041_;
  always @(posedge clk)
      \mem[13] [0] <= _0042_;
  always @(posedge clk)
      \mem[13] [1] <= _0043_;
  always @(posedge clk)
      \mem[13] [2] <= _0044_;
  always @(posedge clk)
      \mem[13] [3] <= _0045_;
  always @(posedge clk)
      \mem[13] [4] <= _0046_;
  always @(posedge clk)
      \mem[13] [5] <= _0047_;
  always @(posedge clk)
      \mem[13] [6] <= _0048_;
  always @(posedge clk)
      \mem[13] [7] <= _0049_;
  always @(posedge clk)
      \mem[13] [8] <= _0050_;
  always @(posedge clk)
      \mem[13] [9] <= _0051_;
endmodule

(* top =  1  *)
(* src = "ib.v:4" *)
module ib(clk, rst, ack, pkti, pkto, full, req);
  (* src = "ib.v:5" *)
  input ack;
  (* src = "ib.v:4" *)
  input clk;
  (* src = "ib.v:14" *)
  wire empty;
  (* src = "ib.v:8" *)
  output full;
  (* src = "ib.v:6" *)
  input [9:0] pkti;
  (* src = "ib.v:7" *)
  output [9:0] pkto;
  (* src = "ib.v:14" *)
  wire re;
  (* src = "ib.v:9" *)
  output [3:0] req;
  (* src = "ib.v:11" *)
  wire [3:0] reqi;
  (* src = "ib.v:4" *)
  input rst;
  (* src = "ib.v:13" *)
  wire we;
  (* module_not_derived = 32'd1 *)
  (* src = "ib.v:14" *)
  fifo fifo (
    .clk(clk),
    .empty(empty),
    .full(full),
    .pkti(pkti),
    .pkto(pkto),
    .re(re),
    .rst(rst),
    .we(we)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "ib.v:15" *)
  ibsm ibsm (
    .ack(ack),
    .clk(clk),
    .empty(empty),
    .pkto(pkto),
    .re(re),
    .req(req),
    .reqi(reqi),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "ib.v:16" *)
  mkreq mkreq (
    .clk(clk),
    .pkto(pkto),
    .reqi(reqi),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "ib.v:13" *)
  mkwe mkwe (
    .pkti(pkti),
    .we(we)
  );
endmodule

(* src = "ibsm.v:4" *)
module ibsm(clk, rst, ack, pkto, reqi, empty, re, req);
  (* src = "ibsm.v:15" *)
  wire [3:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  (* src = "ibsm.v:5" *)
  input ack;
  (* src = "ibsm.v:4" *)
  input clk;
  (* src = "ibsm.v:8" *)
  input empty;
  (* src = "ibsm.v:6" *)
  input [9:0] pkto;
  (* src = "ibsm.v:9" *)
  output re;
  (* src = "ibsm.v:10" *)
  output [3:0] req;
  (* src = "ibsm.v:7" *)
  input [3:0] reqi;
  (* src = "ibsm.v:4" *)
  input rst;
  (* onehot = 32'd1 *)
  reg [2:0] state;
  (* src = "ibsm.v:13" *)
  reg [3:0] tmp;
  assign _004_ = ~state[1];
  assign _005_ = ~state[2];
  assign _006_ = rst | ~(ack);
  assign _007_ = ~rst;
  assign _008_ = pkto[9] & pkto[8];
  assign _009_ = _008_ | ~(_007_);
  assign _002_ = ~((_006_ | _005_) & (_004_ | _009_));
  assign _010_ = ~state[0];
  assign _011_ = empty | rst;
  assign _012_ = ack | rst;
  assign _003_ = ~((_011_ | _010_) & (_005_ | _012_));
  assign _013_ = rst | ~(empty);
  assign _014_ = ~(_008_ & _007_);
  assign _015_ = ~((_013_ | _010_) & (_004_ | _014_));
  assign _001_ = _015_ | ~(_007_);
  assign _016_ = tmp[0] & ~(state[0]);
  assign _017_ = pkto[8] | ~(pkto[9]);
  assign _018_ = _017_ ? _016_ : reqi[0];
  assign _019_ = state[2] ? _018_ : _016_;
  assign _000_[0] = rst ? tmp[0] : _019_;
  assign _020_ = tmp[1] & ~(state[0]);
  assign _021_ = _017_ ? _020_ : reqi[1];
  assign _022_ = state[2] ? _021_ : _020_;
  assign _000_[1] = rst ? tmp[1] : _022_;
  assign _023_ = tmp[2] & ~(state[0]);
  assign _024_ = _017_ ? _023_ : reqi[2];
  assign _025_ = state[2] ? _024_ : _023_;
  assign _000_[2] = rst ? tmp[2] : _025_;
  assign _026_ = tmp[3] & ~(state[0]);
  assign _027_ = _017_ ? _026_ : reqi[3];
  assign _028_ = state[2] ? _027_ : _026_;
  assign _000_[3] = rst ? tmp[3] : _028_;
  assign _029_ = _017_ | ~(reqi[0]);
  assign _030_ = ~(_029_ | empty);
  assign _031_ = state[2] | state[1];
  assign _032_ = _008_ | ~(tmp[0]);
  assign _033_ = ~tmp[0];
  assign _034_ = ~reqi[0];
  assign _035_ = pkto[9] & ~(pkto[8]);
  assign _036_ = _035_ ? _034_ : _033_;
  assign _037_ = ~((_032_ | _004_) & (_005_ | _036_));
  assign req[0] = _031_ ? _037_ : _030_;
  assign _038_ = _017_ | ~(reqi[1]);
  assign _039_ = ~(_038_ | empty);
  assign _040_ = _008_ | ~(tmp[1]);
  assign _041_ = ~tmp[1];
  assign _042_ = ~reqi[1];
  assign _043_ = _035_ ? _042_ : _041_;
  assign _044_ = ~((_040_ | _004_) & (_005_ | _043_));
  assign req[1] = _031_ ? _044_ : _039_;
  assign _045_ = _017_ | ~(reqi[2]);
  assign _046_ = ~(_045_ | empty);
  assign _047_ = _008_ | ~(tmp[2]);
  assign _048_ = ~tmp[2];
  assign _049_ = ~reqi[2];
  assign _050_ = _035_ ? _049_ : _048_;
  assign _051_ = ~((_047_ | _004_) & (_005_ | _050_));
  assign req[2] = _031_ ? _051_ : _046_;
  assign _052_ = _017_ | ~(reqi[3]);
  assign _053_ = ~(_052_ | empty);
  assign _054_ = _008_ | ~(tmp[3]);
  assign _055_ = ~tmp[3];
  assign _056_ = ~reqi[3];
  assign _057_ = _035_ ? _056_ : _055_;
  assign _058_ = ~((_054_ | _004_) & (_005_ | _057_));
  assign req[3] = _031_ ? _058_ : _053_;
  assign _059_ = ~ack;
  assign re = ~((_059_ | _005_) & _004_);
  always @(posedge clk)
      state[0] <= _001_;
  always @(posedge clk)
      state[1] <= _002_;
  always @(posedge clk)
      state[2] <= _003_;
  (* src = "ibsm.v:15" *)
  always @(posedge clk)
      tmp[0] <= _000_[0];
  (* src = "ibsm.v:15" *)
  always @(posedge clk)
      tmp[1] <= _000_[1];
  (* src = "ibsm.v:15" *)
  always @(posedge clk)
      tmp[2] <= _000_[2];
  (* src = "ibsm.v:15" *)
  always @(posedge clk)
      tmp[3] <= _000_[3];
endmodule

(* src = "mkreq.v:3" *)
module mkreq(clk, rst, pkto, reqi);
  (* src = "mkreq.v:9" *)
  wire [3:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  (* src = "mkreq.v:3" *)
  input clk;
  (* src = "mkreq.v:4" *)
  input [9:0] pkto;
  (* src = "mkreq.v:5" *)
  output [3:0] reqi;
  reg [3:0] reqi;
  (* src = "mkreq.v:3" *)
  input rst;
  assign _01_ = ~(pkto[1] | pkto[0]);
  assign _02_ = pkto[9] & ~(pkto[8]);
  assign _03_ = ~(_02_ & _01_);
  assign _00_[0] = ~(_03_ | rst);
  assign _04_ = pkto[1] | ~(pkto[0]);
  assign _05_ = _04_ | ~(_02_);
  assign _00_[1] = ~(_05_ | rst);
  assign _06_ = pkto[0] | ~(pkto[1]);
  assign _07_ = _06_ | ~(_02_);
  assign _00_[2] = ~(_07_ | rst);
  assign _08_ = ~(pkto[1] & pkto[0]);
  assign _09_ = _08_ | ~(_02_);
  assign _00_[3] = ~(_09_ | rst);
  (* src = "mkreq.v:9" *)
  always @(posedge clk)
      reqi[0] <= _00_[0];
  (* src = "mkreq.v:9" *)
  always @(posedge clk)
      reqi[1] <= _00_[1];
  (* src = "mkreq.v:9" *)
  always @(posedge clk)
      reqi[2] <= _00_[2];
  (* src = "mkreq.v:9" *)
  always @(posedge clk)
      reqi[3] <= _00_[3];
endmodule

(* src = "mkwe.v:3" *)
module mkwe(pkti, we);
  (* src = "mkwe.v:3" *)
  input [9:0] pkti;
  (* src = "mkwe.v:3" *)
  output we;
  assign we = pkti[9] | pkti[8];
endmodule
