/* Generated by Yosys 0.9 (git sha1 1979e0b1, i686-w64-mingw32.static-g++ 5.5.0 -Os) */

(* top =  1  *)
(* src = "mkreq.v:3" *)
module mkreq(clk, rst, pkto, reqi);
  (* src = "mkreq.v:9" *)
  wire [3:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  (* src = "mkreq.v:3" *)
  input clk;
  (* src = "mkreq.v:4" *)
  input [9:0] pkto;
  (* src = "mkreq.v:5" *)
  output [3:0] reqi;
  reg [3:0] reqi;
  (* src = "mkreq.v:3" *)
  input rst;
  assign _01_ = ~(pkto[0] | pkto[1]);
  assign _02_ = pkto[9] & ~(pkto[8]);
  assign _03_ = ~(_02_ & _01_);
  assign _00_[0] = ~(_03_ | rst);
  assign _04_ = pkto[1] | ~(pkto[0]);
  assign _05_ = _04_ | ~(_02_);
  assign _00_[1] = ~(_05_ | rst);
  assign _06_ = pkto[0] | ~(pkto[1]);
  assign _07_ = _06_ | ~(_02_);
  assign _00_[2] = ~(_07_ | rst);
  assign _08_ = ~(pkto[0] & pkto[1]);
  assign _09_ = _08_ | ~(_02_);
  assign _00_[3] = ~(_09_ | rst);
  (* src = "mkreq.v:9" *)
  always @(posedge clk)
      reqi[0] <= _00_[0];
  (* src = "mkreq.v:9" *)
  always @(posedge clk)
      reqi[1] <= _00_[1];
  (* src = "mkreq.v:9" *)
  always @(posedge clk)
      reqi[2] <= _00_[2];
  (* src = "mkreq.v:9" *)
  always @(posedge clk)
      reqi[3] <= _00_[3];
endmodule
