/* Generated by Yosys 0.9 (git sha1 1979e0b1, i686-w64-mingw32.static-g++ 5.5.0 -Os) */

(* src = "ackor.v:2" *)
module ackor(ack0, ack1, ack2, ack3, ack);
  wire _0_;
  wire _1_;
  (* src = "ackor.v:3" *)
  output ack;
  (* src = "ackor.v:2" *)
  input ack0;
  (* src = "ackor.v:2" *)
  input ack1;
  (* src = "ackor.v:2" *)
  input ack2;
  (* src = "ackor.v:2" *)
  input ack3;
  assign _0_ = ack1 | ack0;
  assign _1_ = _0_ | ack2;
  assign ack = _1_ | ack3;
endmodule

(* src = "arb.v:7" *)
module arb(clk, rst, req0, req1, req2, req3, ack0, ack1, ack2, ack3);
  (* src = "arb.v:15" *)
  wire _000_;
  (* src = "arb.v:15" *)
  wire _001_;
  (* src = "arb.v:15" *)
  wire _002_;
  (* src = "arb.v:15" *)
  wire _003_;
  (* src = "arb.v:15" *)
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  (* src = "arb.v:9" *)
  output ack0;
  reg ack0;
  (* src = "arb.v:9" *)
  output ack1;
  reg ack1;
  (* src = "arb.v:9" *)
  output ack2;
  reg ack2;
  (* src = "arb.v:9" *)
  output ack3;
  reg ack3;
  (* src = "arb.v:11" *)
  reg check;
  (* src = "arb.v:7" *)
  input clk;
  (* src = "arb.v:8" *)
  input req0;
  (* src = "arb.v:8" *)
  input req1;
  (* src = "arb.v:8" *)
  input req2;
  (* src = "arb.v:8" *)
  input req3;
  (* onehot = 32'd1 *)
  reg [3:0] round;
  (* src = "arb.v:7" *)
  input rst;
  assign _009_ = ~round[3];
  assign _010_ = ~round[1];
  assign _011_ = ~rst;
  assign _012_ = ~req2;
  assign _013_ = req1 | req0;
  assign _014_ = _013_ | ~(_012_);
  assign _015_ = ~(_014_ | req3);
  assign _016_ = ~(_015_ & check);
  assign _017_ = ~(_016_ & _011_);
  assign _018_ = _016_ | ~(_011_);
  assign _008_ = ~((_017_ | _009_) & (_010_ | _018_));
  assign _019_ = ~round[2];
  assign _006_ = ~((_017_ | _010_) & (_019_ | _018_));
  assign _020_ = ~round[0];
  assign _021_ = ~((_017_ | _020_) & (_009_ | _018_));
  assign _005_ = _021_ | ~(_011_);
  assign _007_ = ~((_017_ | _019_) & (_020_ | _018_));
  assign _022_ = ~(req3 ^ req2);
  assign _023_ = ~(_022_ ^ req1);
  assign _024_ = ~req3;
  assign _025_ = _022_ | ~(req1);
  assign _026_ = ~((_024_ | _012_) & _025_);
  assign _027_ = ~((_023_ & req0) | _026_);
  assign _028_ = check ? _015_ : _027_;
  assign _004_ = ~(_028_ | rst);
  assign _029_ = ~req0;
  assign _030_ = req2 | ~(req3);
  assign _031_ = ~(_030_ | req1);
  assign _032_ = ~(_031_ & _029_);
  assign _033_ = round[1] | round[3];
  assign _034_ = ~(_033_ | round[2]);
  assign _035_ = ~_034_;
  assign _036_ = ~((_024_ | _009_) & (_010_ | _030_));
  assign _037_ = ~((_031_ & round[2]) | _036_);
  assign _038_ = _034_ ? _032_ : _037_;
  assign _003_ = ~(_038_ | rst);
  assign _039_ = req1 | ~(req2);
  assign _040_ = _039_ | ~(_029_);
  assign _041_ = _040_ | ~(_034_);
  assign _042_ = _040_ | ~(_024_);
  assign _043_ = ~((_012_ | _010_) & (_009_ | _042_));
  assign _044_ = ~(_039_ | _019_);
  assign _045_ = ~((_044_ | _043_) & _035_);
  assign _002_ = ~((_045_ & _041_) | rst);
  assign _046_ = req0 | ~(req1);
  assign _047_ = _046_ | ~(_034_);
  assign _048_ = _046_ | ~(_024_);
  assign _049_ = _048_ | ~(_012_);
  assign _050_ = ~((_048_ | _009_) & (_010_ | _049_));
  assign _051_ = req1 & round[2];
  assign _052_ = ~((_051_ | _050_) & _035_);
  assign _001_ = ~((_052_ & _047_) | rst);
  assign _053_ = req3 | ~(req0);
  assign _054_ = _053_ | ~(_012_);
  assign _055_ = ~((_053_ | _009_) & (_010_ | _054_));
  assign _056_ = ~(_054_ | req1);
  assign _057_ = ~((_056_ & round[2]) | _055_);
  assign _058_ = _034_ ? _029_ : _057_;
  assign _000_ = ~(_058_ | rst);
  always @(posedge clk)
      round[0] <= _005_;
  always @(posedge clk)
      round[1] <= _006_;
  always @(posedge clk)
      round[2] <= _007_;
  always @(posedge clk)
      round[3] <= _008_;
  (* src = "arb.v:15" *)
  always @(posedge clk)
      ack0 <= _000_;
  (* src = "arb.v:15" *)
  always @(posedge clk)
      ack1 <= _001_;
  (* src = "arb.v:15" *)
  always @(posedge clk)
      ack2 <= _002_;
  (* src = "arb.v:15" *)
  always @(posedge clk)
      ack3 <= _003_;
  (* src = "arb.v:15" *)
  always @(posedge clk)
      check <= _004_;
endmodule

(* src = "cb.v:5" *)
module cb(co0, co1, co2, co3, ack0, ack1, ack2, ack3, o0, o1, o2, o3);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  (* src = "cb.v:6" *)
  input [3:0] ack0;
  (* src = "cb.v:6" *)
  input [3:0] ack1;
  (* src = "cb.v:6" *)
  input [3:0] ack2;
  (* src = "cb.v:6" *)
  input [3:0] ack3;
  (* src = "cb.v:5" *)
  input [9:0] co0;
  (* src = "cb.v:5" *)
  input [9:0] co1;
  (* src = "cb.v:5" *)
  input [9:0] co2;
  (* src = "cb.v:5" *)
  input [9:0] co3;
  (* src = "cb.v:7" *)
  output [9:0] o0;
  (* src = "cb.v:7" *)
  output [9:0] o1;
  (* src = "cb.v:7" *)
  output [9:0] o2;
  (* src = "cb.v:7" *)
  output [9:0] o3;
  assign _000_ = ack3[0] & co0[0];
  assign _001_ = ack3[1] ? co1[0] : _000_;
  assign _002_ = ack3[2] ? co2[0] : _001_;
  assign o3[0] = ack3[3] ? co3[0] : _002_;
  assign _003_ = co0[1] & ack3[0];
  assign _004_ = ack3[1] ? co1[1] : _003_;
  assign _005_ = ack3[2] ? co2[1] : _004_;
  assign o3[1] = ack3[3] ? co3[1] : _005_;
  assign _006_ = co0[2] & ack3[0];
  assign _007_ = ack3[1] ? co1[2] : _006_;
  assign _008_ = ack3[2] ? co2[2] : _007_;
  assign o3[2] = ack3[3] ? co3[2] : _008_;
  assign _009_ = co0[3] & ack3[0];
  assign _010_ = ack3[1] ? co1[3] : _009_;
  assign _011_ = ack3[2] ? co2[3] : _010_;
  assign o3[3] = ack3[3] ? co3[3] : _011_;
  assign _012_ = co0[4] & ack3[0];
  assign _013_ = ack3[1] ? co1[4] : _012_;
  assign _014_ = ack3[2] ? co2[4] : _013_;
  assign o3[4] = ack3[3] ? co3[4] : _014_;
  assign _015_ = co0[5] & ack3[0];
  assign _016_ = ack3[1] ? co1[5] : _015_;
  assign _017_ = ack3[2] ? co2[5] : _016_;
  assign o3[5] = ack3[3] ? co3[5] : _017_;
  assign _018_ = co0[6] & ack3[0];
  assign _019_ = ack3[1] ? co1[6] : _018_;
  assign _020_ = ack3[2] ? co2[6] : _019_;
  assign o3[6] = ack3[3] ? co3[6] : _020_;
  assign _021_ = co0[7] & ack3[0];
  assign _022_ = ack3[1] ? co1[7] : _021_;
  assign _023_ = ack3[2] ? co2[7] : _022_;
  assign o3[7] = ack3[3] ? co3[7] : _023_;
  assign _024_ = co0[8] & ack3[0];
  assign _025_ = ack3[1] ? co1[8] : _024_;
  assign _026_ = ack3[2] ? co2[8] : _025_;
  assign o3[8] = ack3[3] ? co3[8] : _026_;
  assign _027_ = co0[9] & ack3[0];
  assign _028_ = ack3[1] ? co1[9] : _027_;
  assign _029_ = ack3[2] ? co2[9] : _028_;
  assign o3[9] = ack3[3] ? co3[9] : _029_;
  assign _030_ = ack2[0] & co0[0];
  assign _031_ = ack2[1] ? co1[0] : _030_;
  assign _032_ = ack2[2] ? co2[0] : _031_;
  assign o2[0] = ack2[3] ? co3[0] : _032_;
  assign _033_ = ack2[0] & co0[1];
  assign _034_ = ack2[1] ? co1[1] : _033_;
  assign _035_ = ack2[2] ? co2[1] : _034_;
  assign o2[1] = ack2[3] ? co3[1] : _035_;
  assign _036_ = ack2[0] & co0[2];
  assign _037_ = ack2[1] ? co1[2] : _036_;
  assign _038_ = ack2[2] ? co2[2] : _037_;
  assign o2[2] = ack2[3] ? co3[2] : _038_;
  assign _039_ = ack2[0] & co0[3];
  assign _040_ = ack2[1] ? co1[3] : _039_;
  assign _041_ = ack2[2] ? co2[3] : _040_;
  assign o2[3] = ack2[3] ? co3[3] : _041_;
  assign _042_ = ack2[0] & co0[4];
  assign _043_ = ack2[1] ? co1[4] : _042_;
  assign _044_ = ack2[2] ? co2[4] : _043_;
  assign o2[4] = ack2[3] ? co3[4] : _044_;
  assign _045_ = ack2[0] & co0[5];
  assign _046_ = ack2[1] ? co1[5] : _045_;
  assign _047_ = ack2[2] ? co2[5] : _046_;
  assign o2[5] = ack2[3] ? co3[5] : _047_;
  assign _048_ = ack2[0] & co0[6];
  assign _049_ = ack2[1] ? co1[6] : _048_;
  assign _050_ = ack2[2] ? co2[6] : _049_;
  assign o2[6] = ack2[3] ? co3[6] : _050_;
  assign _051_ = ack2[0] & co0[7];
  assign _052_ = ack2[1] ? co1[7] : _051_;
  assign _053_ = ack2[2] ? co2[7] : _052_;
  assign o2[7] = ack2[3] ? co3[7] : _053_;
  assign _054_ = ack2[0] & co0[8];
  assign _055_ = ack2[1] ? co1[8] : _054_;
  assign _056_ = ack2[2] ? co2[8] : _055_;
  assign o2[8] = ack2[3] ? co3[8] : _056_;
  assign _057_ = ack2[0] & co0[9];
  assign _058_ = ack2[1] ? co1[9] : _057_;
  assign _059_ = ack2[2] ? co2[9] : _058_;
  assign o2[9] = ack2[3] ? co3[9] : _059_;
  assign _060_ = ack1[0] & co0[0];
  assign _061_ = ack1[1] ? co1[0] : _060_;
  assign _062_ = ack1[2] ? co2[0] : _061_;
  assign o1[0] = ack1[3] ? co3[0] : _062_;
  assign _063_ = ack1[0] & co0[1];
  assign _064_ = ack1[1] ? co1[1] : _063_;
  assign _065_ = ack1[2] ? co2[1] : _064_;
  assign o1[1] = ack1[3] ? co3[1] : _065_;
  assign _066_ = ack1[0] & co0[2];
  assign _067_ = ack1[1] ? co1[2] : _066_;
  assign _068_ = ack1[2] ? co2[2] : _067_;
  assign o1[2] = ack1[3] ? co3[2] : _068_;
  assign _069_ = ack1[0] & co0[3];
  assign _070_ = ack1[1] ? co1[3] : _069_;
  assign _071_ = ack1[2] ? co2[3] : _070_;
  assign o1[3] = ack1[3] ? co3[3] : _071_;
  assign _072_ = ack1[0] & co0[4];
  assign _073_ = ack1[1] ? co1[4] : _072_;
  assign _074_ = ack1[2] ? co2[4] : _073_;
  assign o1[4] = ack1[3] ? co3[4] : _074_;
  assign _075_ = ack1[0] & co0[5];
  assign _076_ = ack1[1] ? co1[5] : _075_;
  assign _077_ = ack1[2] ? co2[5] : _076_;
  assign o1[5] = ack1[3] ? co3[5] : _077_;
  assign _078_ = ack1[0] & co0[6];
  assign _079_ = ack1[1] ? co1[6] : _078_;
  assign _080_ = ack1[2] ? co2[6] : _079_;
  assign o1[6] = ack1[3] ? co3[6] : _080_;
  assign _081_ = ack1[0] & co0[7];
  assign _082_ = ack1[1] ? co1[7] : _081_;
  assign _083_ = ack1[2] ? co2[7] : _082_;
  assign o1[7] = ack1[3] ? co3[7] : _083_;
  assign _084_ = ack1[0] & co0[8];
  assign _085_ = ack1[1] ? co1[8] : _084_;
  assign _086_ = ack1[2] ? co2[8] : _085_;
  assign o1[8] = ack1[3] ? co3[8] : _086_;
  assign _087_ = ack1[0] & co0[9];
  assign _088_ = ack1[1] ? co1[9] : _087_;
  assign _089_ = ack1[2] ? co2[9] : _088_;
  assign o1[9] = ack1[3] ? co3[9] : _089_;
  assign _090_ = ack0[0] & co0[0];
  assign _091_ = ack0[1] ? co1[0] : _090_;
  assign _092_ = ack0[2] ? co2[0] : _091_;
  assign o0[0] = ack0[3] ? co3[0] : _092_;
  assign _093_ = ack0[0] & co0[1];
  assign _094_ = ack0[1] ? co1[1] : _093_;
  assign _095_ = ack0[2] ? co2[1] : _094_;
  assign o0[1] = ack0[3] ? co3[1] : _095_;
  assign _096_ = ack0[0] & co0[2];
  assign _097_ = ack0[1] ? co1[2] : _096_;
  assign _098_ = ack0[2] ? co2[2] : _097_;
  assign o0[2] = ack0[3] ? co3[2] : _098_;
  assign _099_ = ack0[0] & co0[3];
  assign _100_ = ack0[1] ? co1[3] : _099_;
  assign _101_ = ack0[2] ? co2[3] : _100_;
  assign o0[3] = ack0[3] ? co3[3] : _101_;
  assign _102_ = ack0[0] & co0[4];
  assign _103_ = ack0[1] ? co1[4] : _102_;
  assign _104_ = ack0[2] ? co2[4] : _103_;
  assign o0[4] = ack0[3] ? co3[4] : _104_;
  assign _105_ = ack0[0] & co0[5];
  assign _106_ = ack0[1] ? co1[5] : _105_;
  assign _107_ = ack0[2] ? co2[5] : _106_;
  assign o0[5] = ack0[3] ? co3[5] : _107_;
  assign _108_ = ack0[0] & co0[6];
  assign _109_ = ack0[1] ? co1[6] : _108_;
  assign _110_ = ack0[2] ? co2[6] : _109_;
  assign o0[6] = ack0[3] ? co3[6] : _110_;
  assign _111_ = ack0[0] & co0[7];
  assign _112_ = ack0[1] ? co1[7] : _111_;
  assign _113_ = ack0[2] ? co2[7] : _112_;
  assign o0[7] = ack0[3] ? co3[7] : _113_;
  assign _114_ = ack0[0] & co0[8];
  assign _115_ = ack0[1] ? co1[8] : _114_;
  assign _116_ = ack0[2] ? co2[8] : _115_;
  assign o0[8] = ack0[3] ? co3[8] : _116_;
  assign _117_ = ack0[0] & co0[9];
  assign _118_ = ack0[1] ? co1[9] : _117_;
  assign _119_ = ack0[2] ? co2[9] : _118_;
  assign o0[9] = ack0[3] ? co3[9] : _119_;
endmodule

(* src = "fifo.v:6" *)
module fifo(clk, rst, re, we, pkti, empty, full, pkto);
  (* src = "fifo.v:16" *)
  wire [3:0] _0000_;
  (* src = "fifo.v:16" *)
  wire [3:0] _0001_;
  wire _0002_;
  wire _0003_;
  wire _0004_;
  wire _0005_;
  wire _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  wire _0430_;
  wire _0431_;
  wire _0432_;
  wire _0433_;
  wire _0434_;
  wire _0435_;
  wire _0436_;
  wire _0437_;
  wire _0438_;
  wire _0439_;
  wire _0440_;
  wire _0441_;
  wire _0442_;
  wire _0443_;
  wire _0444_;
  wire _0445_;
  wire _0446_;
  wire _0447_;
  wire _0448_;
  wire _0449_;
  wire _0450_;
  wire _0451_;
  wire _0452_;
  wire _0453_;
  wire _0454_;
  wire _0455_;
  wire _0456_;
  wire _0457_;
  wire _0458_;
  wire _0459_;
  wire _0460_;
  wire _0461_;
  wire _0462_;
  wire _0463_;
  wire _0464_;
  wire _0465_;
  wire _0466_;
  wire _0467_;
  wire _0468_;
  wire _0469_;
  wire _0470_;
  wire _0471_;
  wire _0472_;
  wire _0473_;
  wire _0474_;
  wire _0475_;
  wire _0476_;
  wire _0477_;
  wire _0478_;
  wire _0479_;
  wire _0480_;
  wire _0481_;
  wire _0482_;
  wire _0483_;
  wire _0484_;
  wire _0485_;
  wire _0486_;
  wire _0487_;
  wire _0488_;
  wire _0489_;
  wire _0490_;
  wire _0491_;
  wire _0492_;
  wire _0493_;
  wire _0494_;
  wire _0495_;
  wire _0496_;
  wire _0497_;
  wire _0498_;
  wire _0499_;
  wire _0500_;
  wire _0501_;
  wire _0502_;
  wire _0503_;
  wire _0504_;
  wire _0505_;
  wire _0506_;
  wire _0507_;
  wire _0508_;
  wire _0509_;
  wire _0510_;
  wire _0511_;
  wire _0512_;
  wire _0513_;
  wire _0514_;
  wire _0515_;
  wire _0516_;
  wire _0517_;
  wire _0518_;
  wire _0519_;
  wire _0520_;
  wire _0521_;
  wire _0522_;
  wire _0523_;
  wire _0524_;
  wire _0525_;
  wire _0526_;
  wire _0527_;
  wire _0528_;
  wire _0529_;
  wire _0530_;
  wire _0531_;
  wire _0532_;
  wire _0533_;
  wire _0534_;
  wire _0535_;
  wire _0536_;
  wire _0537_;
  wire _0538_;
  wire _0539_;
  wire _0540_;
  wire _0541_;
  wire _0542_;
  wire _0543_;
  wire _0544_;
  wire _0545_;
  wire _0546_;
  wire _0547_;
  wire _0548_;
  wire _0549_;
  wire _0550_;
  wire _0551_;
  wire _0552_;
  wire _0553_;
  wire _0554_;
  wire _0555_;
  wire _0556_;
  wire _0557_;
  wire _0558_;
  wire _0559_;
  wire _0560_;
  wire _0561_;
  wire _0562_;
  wire _0563_;
  wire _0564_;
  wire _0565_;
  wire _0566_;
  wire _0567_;
  wire _0568_;
  wire _0569_;
  wire _0570_;
  wire _0571_;
  wire _0572_;
  wire _0573_;
  wire _0574_;
  wire _0575_;
  wire _0576_;
  wire _0577_;
  wire _0578_;
  wire _0579_;
  wire _0580_;
  wire _0581_;
  wire _0582_;
  wire _0583_;
  wire _0584_;
  wire _0585_;
  wire _0586_;
  wire _0587_;
  wire _0588_;
  wire _0589_;
  wire _0590_;
  wire _0591_;
  wire _0592_;
  wire _0593_;
  wire _0594_;
  wire _0595_;
  wire _0596_;
  wire _0597_;
  wire _0598_;
  wire _0599_;
  wire _0600_;
  wire _0601_;
  wire _0602_;
  wire _0603_;
  wire _0604_;
  wire _0605_;
  wire _0606_;
  wire _0607_;
  wire _0608_;
  wire _0609_;
  wire _0610_;
  wire _0611_;
  wire _0612_;
  wire _0613_;
  wire _0614_;
  wire _0615_;
  wire _0616_;
  wire _0617_;
  wire _0618_;
  wire _0619_;
  wire _0620_;
  wire _0621_;
  wire _0622_;
  wire _0623_;
  wire _0624_;
  wire _0625_;
  wire _0626_;
  wire _0627_;
  wire _0628_;
  wire _0629_;
  wire _0630_;
  wire _0631_;
  wire _0632_;
  wire _0633_;
  wire _0634_;
  wire _0635_;
  wire _0636_;
  wire _0637_;
  wire _0638_;
  wire _0639_;
  wire _0640_;
  wire _0641_;
  wire _0642_;
  wire _0643_;
  wire _0644_;
  wire _0645_;
  wire _0646_;
  wire _0647_;
  wire _0648_;
  wire _0649_;
  wire _0650_;
  wire _0651_;
  wire _0652_;
  wire _0653_;
  wire _0654_;
  wire _0655_;
  wire _0656_;
  wire _0657_;
  wire _0658_;
  wire _0659_;
  wire _0660_;
  wire _0661_;
  wire _0662_;
  wire _0663_;
  wire _0664_;
  wire _0665_;
  wire _0666_;
  wire _0667_;
  wire _0668_;
  wire _0669_;
  wire _0670_;
  wire _0671_;
  wire _0672_;
  wire _0673_;
  wire _0674_;
  wire _0675_;
  wire _0676_;
  wire _0677_;
  wire _0678_;
  wire _0679_;
  wire _0680_;
  wire _0681_;
  wire _0682_;
  wire _0683_;
  wire _0684_;
  wire _0685_;
  wire _0686_;
  wire _0687_;
  wire _0688_;
  wire _0689_;
  wire _0690_;
  wire _0691_;
  wire _0692_;
  wire _0693_;
  wire _0694_;
  wire _0695_;
  wire _0696_;
  wire _0697_;
  wire _0698_;
  wire _0699_;
  wire _0700_;
  wire _0701_;
  wire _0702_;
  wire _0703_;
  wire _0704_;
  wire _0705_;
  wire _0706_;
  wire _0707_;
  wire _0708_;
  wire _0709_;
  wire _0710_;
  wire _0711_;
  wire _0712_;
  wire _0713_;
  wire _0714_;
  wire _0715_;
  wire _0716_;
  wire _0717_;
  wire _0718_;
  wire _0719_;
  wire _0720_;
  wire _0721_;
  wire _0722_;
  wire _0723_;
  wire _0724_;
  wire _0725_;
  wire _0726_;
  wire _0727_;
  wire _0728_;
  wire _0729_;
  wire _0730_;
  wire _0731_;
  wire _0732_;
  wire _0733_;
  wire _0734_;
  wire _0735_;
  wire _0736_;
  wire _0737_;
  wire _0738_;
  wire _0739_;
  wire _0740_;
  wire _0741_;
  wire _0742_;
  wire _0743_;
  wire _0744_;
  wire _0745_;
  wire _0746_;
  wire _0747_;
  wire _0748_;
  wire _0749_;
  wire _0750_;
  wire _0751_;
  wire _0752_;
  wire _0753_;
  wire _0754_;
  wire _0755_;
  wire _0756_;
  (* src = "fifo.v:6" *)
  input clk;
  (* src = "fifo.v:9" *)
  output empty;
  (* src = "fifo.v:9" *)
  output full;
  (* src = "fifo.v:13" *)
  reg [3:0] head;
  reg [9:0] \mem[0] ;
  reg [9:0] \mem[10] ;
  reg [9:0] \mem[11] ;
  reg [9:0] \mem[12] ;
  reg [9:0] \mem[13] ;
  reg [9:0] \mem[14] ;
  reg [9:0] \mem[15] ;
  reg [9:0] \mem[1] ;
  reg [9:0] \mem[2] ;
  reg [9:0] \mem[3] ;
  reg [9:0] \mem[4] ;
  reg [9:0] \mem[5] ;
  reg [9:0] \mem[6] ;
  reg [9:0] \mem[7] ;
  reg [9:0] \mem[8] ;
  reg [9:0] \mem[9] ;
  (* src = "fifo.v:8" *)
  input [9:0] pkti;
  (* src = "fifo.v:10" *)
  output [9:0] pkto;
  (* src = "fifo.v:7" *)
  input re;
  (* src = "fifo.v:6" *)
  input rst;
  (* src = "fifo.v:13" *)
  reg [3:0] tail;
  (* src = "fifo.v:7" *)
  input we;
  assign _0258_ = ~(head[0] ^ tail[0]);
  assign _0259_ = head[1] ^ tail[1];
  assign _0260_ = _0259_ | ~(_0258_);
  assign _0261_ = ~(head[2] ^ tail[2]);
  assign _0262_ = tail[3] ^ head[3];
  assign _0263_ = _0262_ | ~(_0261_);
  assign empty = ~(_0263_ | _0260_);
  assign _0264_ = head[0] ^ tail[0];
  assign _0265_ = ~(head[1] ^ head[0]);
  assign _0266_ = ~(_0265_ ^ tail[1]);
  assign _0267_ = _0266_ | ~(_0264_);
  assign _0268_ = ~tail[2];
  assign _0269_ = head[1] & head[0];
  assign _0270_ = ~(_0269_ ^ head[2]);
  assign _0271_ = ~(_0270_ ^ _0268_);
  assign _0272_ = ~head[2];
  assign _0273_ = _0269_ & ~(_0272_);
  assign _0274_ = ~(_0273_ ^ head[3]);
  assign _0275_ = ~(_0274_ ^ tail[3]);
  assign _0276_ = _0275_ | ~(_0271_);
  assign full = ~(_0276_ | _0267_);
  assign _0277_ = tail[0] ? \mem[1] [0] : \mem[0] [0];
  assign _0278_ = tail[0] ? \mem[3] [0] : \mem[2] [0];
  assign _0279_ = tail[1] ? _0278_ : _0277_;
  assign _0280_ = tail[0] ? \mem[5] [0] : \mem[4] [0];
  assign _0281_ = tail[0] ? \mem[7] [0] : \mem[6] [0];
  assign _0282_ = tail[1] ? _0281_ : _0280_;
  assign _0283_ = tail[2] ? _0282_ : _0279_;
  assign _0284_ = tail[0] ? \mem[9] [0] : \mem[8] [0];
  assign _0285_ = tail[0] ? \mem[11] [0] : \mem[10] [0];
  assign _0286_ = tail[1] ? _0285_ : _0284_;
  assign _0287_ = tail[0] ? \mem[13] [0] : \mem[12] [0];
  assign _0288_ = tail[0] ? \mem[15] [0] : \mem[14] [0];
  assign _0289_ = tail[1] ? _0288_ : _0287_;
  assign _0290_ = tail[2] ? _0289_ : _0286_;
  assign pkto[0] = tail[3] ? _0290_ : _0283_;
  assign _0291_ = tail[0] ? \mem[1] [1] : \mem[0] [1];
  assign _0292_ = tail[0] ? \mem[3] [1] : \mem[2] [1];
  assign _0293_ = tail[1] ? _0292_ : _0291_;
  assign _0294_ = tail[0] ? \mem[5] [1] : \mem[4] [1];
  assign _0295_ = tail[0] ? \mem[7] [1] : \mem[6] [1];
  assign _0296_ = tail[1] ? _0295_ : _0294_;
  assign _0297_ = tail[2] ? _0296_ : _0293_;
  assign _0298_ = tail[0] ? \mem[9] [1] : \mem[8] [1];
  assign _0299_ = tail[0] ? \mem[11] [1] : \mem[10] [1];
  assign _0300_ = tail[1] ? _0299_ : _0298_;
  assign _0301_ = tail[0] ? \mem[13] [1] : \mem[12] [1];
  assign _0302_ = tail[0] ? \mem[15] [1] : \mem[14] [1];
  assign _0303_ = tail[1] ? _0302_ : _0301_;
  assign _0304_ = tail[2] ? _0303_ : _0300_;
  assign pkto[1] = tail[3] ? _0304_ : _0297_;
  assign _0305_ = tail[0] ? \mem[1] [2] : \mem[0] [2];
  assign _0306_ = tail[0] ? \mem[3] [2] : \mem[2] [2];
  assign _0307_ = tail[1] ? _0306_ : _0305_;
  assign _0308_ = tail[0] ? \mem[5] [2] : \mem[4] [2];
  assign _0309_ = tail[0] ? \mem[7] [2] : \mem[6] [2];
  assign _0310_ = tail[1] ? _0309_ : _0308_;
  assign _0311_ = tail[2] ? _0310_ : _0307_;
  assign _0312_ = tail[0] ? \mem[9] [2] : \mem[8] [2];
  assign _0313_ = tail[0] ? \mem[11] [2] : \mem[10] [2];
  assign _0314_ = tail[1] ? _0313_ : _0312_;
  assign _0315_ = tail[0] ? \mem[13] [2] : \mem[12] [2];
  assign _0316_ = tail[0] ? \mem[15] [2] : \mem[14] [2];
  assign _0317_ = tail[1] ? _0316_ : _0315_;
  assign _0318_ = tail[2] ? _0317_ : _0314_;
  assign pkto[2] = tail[3] ? _0318_ : _0311_;
  assign _0319_ = tail[0] ? \mem[1] [3] : \mem[0] [3];
  assign _0320_ = tail[0] ? \mem[3] [3] : \mem[2] [3];
  assign _0321_ = tail[1] ? _0320_ : _0319_;
  assign _0322_ = tail[0] ? \mem[5] [3] : \mem[4] [3];
  assign _0323_ = tail[0] ? \mem[7] [3] : \mem[6] [3];
  assign _0324_ = tail[1] ? _0323_ : _0322_;
  assign _0325_ = tail[2] ? _0324_ : _0321_;
  assign _0326_ = tail[0] ? \mem[9] [3] : \mem[8] [3];
  assign _0327_ = tail[0] ? \mem[11] [3] : \mem[10] [3];
  assign _0328_ = tail[1] ? _0327_ : _0326_;
  assign _0329_ = tail[0] ? \mem[13] [3] : \mem[12] [3];
  assign _0330_ = tail[0] ? \mem[15] [3] : \mem[14] [3];
  assign _0331_ = tail[1] ? _0330_ : _0329_;
  assign _0332_ = tail[2] ? _0331_ : _0328_;
  assign pkto[3] = tail[3] ? _0332_ : _0325_;
  assign _0333_ = tail[0] ? \mem[1] [4] : \mem[0] [4];
  assign _0334_ = tail[0] ? \mem[3] [4] : \mem[2] [4];
  assign _0335_ = tail[1] ? _0334_ : _0333_;
  assign _0336_ = tail[0] ? \mem[5] [4] : \mem[4] [4];
  assign _0337_ = tail[0] ? \mem[7] [4] : \mem[6] [4];
  assign _0338_ = tail[1] ? _0337_ : _0336_;
  assign _0339_ = tail[2] ? _0338_ : _0335_;
  assign _0340_ = tail[0] ? \mem[9] [4] : \mem[8] [4];
  assign _0341_ = tail[0] ? \mem[11] [4] : \mem[10] [4];
  assign _0342_ = tail[1] ? _0341_ : _0340_;
  assign _0343_ = tail[0] ? \mem[13] [4] : \mem[12] [4];
  assign _0344_ = tail[0] ? \mem[15] [4] : \mem[14] [4];
  assign _0345_ = tail[1] ? _0344_ : _0343_;
  assign _0346_ = tail[2] ? _0345_ : _0342_;
  assign pkto[4] = tail[3] ? _0346_ : _0339_;
  assign _0347_ = tail[0] ? \mem[1] [5] : \mem[0] [5];
  assign _0348_ = tail[0] ? \mem[3] [5] : \mem[2] [5];
  assign _0349_ = tail[1] ? _0348_ : _0347_;
  assign _0350_ = tail[0] ? \mem[5] [5] : \mem[4] [5];
  assign _0351_ = tail[0] ? \mem[7] [5] : \mem[6] [5];
  assign _0352_ = tail[1] ? _0351_ : _0350_;
  assign _0353_ = tail[2] ? _0352_ : _0349_;
  assign _0354_ = tail[0] ? \mem[9] [5] : \mem[8] [5];
  assign _0355_ = tail[0] ? \mem[11] [5] : \mem[10] [5];
  assign _0356_ = tail[1] ? _0355_ : _0354_;
  assign _0357_ = tail[0] ? \mem[13] [5] : \mem[12] [5];
  assign _0358_ = tail[0] ? \mem[15] [5] : \mem[14] [5];
  assign _0359_ = tail[1] ? _0358_ : _0357_;
  assign _0360_ = tail[2] ? _0359_ : _0356_;
  assign pkto[5] = tail[3] ? _0360_ : _0353_;
  assign _0361_ = tail[0] ? \mem[1] [6] : \mem[0] [6];
  assign _0362_ = tail[0] ? \mem[3] [6] : \mem[2] [6];
  assign _0363_ = tail[1] ? _0362_ : _0361_;
  assign _0364_ = tail[0] ? \mem[5] [6] : \mem[4] [6];
  assign _0365_ = tail[0] ? \mem[7] [6] : \mem[6] [6];
  assign _0366_ = tail[1] ? _0365_ : _0364_;
  assign _0367_ = tail[2] ? _0366_ : _0363_;
  assign _0368_ = tail[0] ? \mem[9] [6] : \mem[8] [6];
  assign _0369_ = tail[0] ? \mem[11] [6] : \mem[10] [6];
  assign _0370_ = tail[1] ? _0369_ : _0368_;
  assign _0371_ = tail[0] ? \mem[13] [6] : \mem[12] [6];
  assign _0372_ = tail[0] ? \mem[15] [6] : \mem[14] [6];
  assign _0373_ = tail[1] ? _0372_ : _0371_;
  assign _0374_ = tail[2] ? _0373_ : _0370_;
  assign pkto[6] = tail[3] ? _0374_ : _0367_;
  assign _0375_ = tail[0] ? \mem[1] [7] : \mem[0] [7];
  assign _0376_ = tail[0] ? \mem[3] [7] : \mem[2] [7];
  assign _0377_ = tail[1] ? _0376_ : _0375_;
  assign _0378_ = tail[0] ? \mem[5] [7] : \mem[4] [7];
  assign _0379_ = tail[0] ? \mem[7] [7] : \mem[6] [7];
  assign _0380_ = tail[1] ? _0379_ : _0378_;
  assign _0381_ = tail[2] ? _0380_ : _0377_;
  assign _0382_ = tail[0] ? \mem[9] [7] : \mem[8] [7];
  assign _0383_ = tail[0] ? \mem[11] [7] : \mem[10] [7];
  assign _0384_ = tail[1] ? _0383_ : _0382_;
  assign _0385_ = tail[0] ? \mem[13] [7] : \mem[12] [7];
  assign _0386_ = tail[0] ? \mem[15] [7] : \mem[14] [7];
  assign _0387_ = tail[1] ? _0386_ : _0385_;
  assign _0388_ = tail[2] ? _0387_ : _0384_;
  assign pkto[7] = tail[3] ? _0388_ : _0381_;
  assign _0389_ = tail[0] ? \mem[1] [8] : \mem[0] [8];
  assign _0390_ = tail[0] ? \mem[3] [8] : \mem[2] [8];
  assign _0391_ = tail[1] ? _0390_ : _0389_;
  assign _0392_ = tail[0] ? \mem[5] [8] : \mem[4] [8];
  assign _0393_ = tail[0] ? \mem[7] [8] : \mem[6] [8];
  assign _0394_ = tail[1] ? _0393_ : _0392_;
  assign _0395_ = tail[2] ? _0394_ : _0391_;
  assign _0396_ = tail[0] ? \mem[9] [8] : \mem[8] [8];
  assign _0397_ = tail[0] ? \mem[11] [8] : \mem[10] [8];
  assign _0398_ = tail[1] ? _0397_ : _0396_;
  assign _0399_ = tail[0] ? \mem[13] [8] : \mem[12] [8];
  assign _0400_ = tail[0] ? \mem[15] [8] : \mem[14] [8];
  assign _0401_ = tail[1] ? _0400_ : _0399_;
  assign _0402_ = tail[2] ? _0401_ : _0398_;
  assign pkto[8] = tail[3] ? _0402_ : _0395_;
  assign _0403_ = tail[0] ? \mem[1] [9] : \mem[0] [9];
  assign _0404_ = tail[0] ? \mem[3] [9] : \mem[2] [9];
  assign _0405_ = tail[1] ? _0404_ : _0403_;
  assign _0406_ = tail[0] ? \mem[5] [9] : \mem[4] [9];
  assign _0407_ = tail[0] ? \mem[7] [9] : \mem[6] [9];
  assign _0408_ = tail[1] ? _0407_ : _0406_;
  assign _0409_ = tail[2] ? _0408_ : _0405_;
  assign _0410_ = tail[0] ? \mem[9] [9] : \mem[8] [9];
  assign _0411_ = tail[0] ? \mem[11] [9] : \mem[10] [9];
  assign _0412_ = tail[1] ? _0411_ : _0410_;
  assign _0413_ = tail[0] ? \mem[13] [9] : \mem[12] [9];
  assign _0414_ = tail[0] ? \mem[15] [9] : \mem[14] [9];
  assign _0415_ = tail[1] ? _0414_ : _0413_;
  assign _0416_ = tail[2] ? _0415_ : _0412_;
  assign pkto[9] = tail[3] ? _0416_ : _0409_;
  assign _0417_ = ~\mem[15] [0];
  assign _0418_ = rst | ~(we);
  assign _0419_ = _0418_ | ~(head[0]);
  assign _0420_ = _0418_ | ~(head[1]);
  assign _0421_ = ~(_0420_ | _0419_);
  assign _0422_ = _0418_ | ~(head[2]);
  assign _0423_ = _0418_ | ~(head[3]);
  assign _0424_ = ~(_0423_ | _0422_);
  assign _0425_ = ~(_0424_ & _0421_);
  assign _0426_ = ~(rst | we);
  assign _0427_ = ~(_0426_ | _0425_);
  assign _0428_ = _0418_ | ~(pkti[0]);
  assign _0429_ = _0427_ ? _0428_ : _0417_;
  assign _0430_ = head[1] & ~(head[0]);
  assign _0431_ = ~(_0274_ | _0270_);
  assign _0432_ = ~(_0431_ & _0430_);
  assign _0433_ = ~(_0432_ | _0418_);
  assign _0062_ = ~(_0433_ | _0429_);
  assign _0434_ = ~\mem[15] [1];
  assign _0435_ = _0418_ | ~(pkti[1]);
  assign _0436_ = _0427_ ? _0435_ : _0434_;
  assign _0063_ = ~(_0436_ | _0433_);
  assign _0437_ = ~\mem[15] [2];
  assign _0438_ = _0418_ | ~(pkti[2]);
  assign _0439_ = _0427_ ? _0438_ : _0437_;
  assign _0064_ = ~(_0439_ | _0433_);
  assign _0440_ = ~\mem[15] [3];
  assign _0441_ = _0418_ | ~(pkti[3]);
  assign _0442_ = _0427_ ? _0441_ : _0440_;
  assign _0065_ = ~(_0442_ | _0433_);
  assign _0443_ = ~\mem[15] [4];
  assign _0444_ = _0418_ | ~(pkti[4]);
  assign _0445_ = _0427_ ? _0444_ : _0443_;
  assign _0066_ = ~(_0445_ | _0433_);
  assign _0446_ = ~\mem[15] [5];
  assign _0447_ = _0418_ | ~(pkti[5]);
  assign _0448_ = _0427_ ? _0447_ : _0446_;
  assign _0067_ = ~(_0448_ | _0433_);
  assign _0449_ = ~\mem[15] [6];
  assign _0450_ = _0418_ | ~(pkti[6]);
  assign _0451_ = _0427_ ? _0450_ : _0449_;
  assign _0068_ = ~(_0451_ | _0433_);
  assign _0452_ = ~\mem[15] [7];
  assign _0453_ = _0418_ | ~(pkti[7]);
  assign _0454_ = _0427_ ? _0453_ : _0452_;
  assign _0069_ = ~(_0454_ | _0433_);
  assign _0455_ = ~\mem[15] [8];
  assign _0456_ = _0418_ | ~(pkti[8]);
  assign _0457_ = _0427_ ? _0456_ : _0455_;
  assign _0070_ = ~(_0457_ | _0433_);
  assign _0458_ = ~\mem[15] [9];
  assign _0459_ = _0418_ | ~(pkti[9]);
  assign _0460_ = _0427_ ? _0459_ : _0458_;
  assign _0071_ = ~(_0460_ | _0433_);
  assign _0461_ = ~(re ^ tail[0]);
  assign _0001_[0] = ~(_0461_ | rst);
  assign _0462_ = ~tail[1];
  assign _0463_ = ~(tail[0] ^ tail[1]);
  assign _0464_ = re ? _0463_ : _0462_;
  assign _0001_[1] = ~(_0464_ | rst);
  assign _0465_ = ~(tail[0] & tail[1]);
  assign _0466_ = ~(_0465_ ^ _0268_);
  assign _0467_ = re ? _0466_ : _0268_;
  assign _0001_[2] = ~(_0467_ | rst);
  assign _0468_ = ~tail[3];
  assign _0469_ = ~(_0465_ | _0268_);
  assign _0470_ = ~(_0469_ ^ tail[3]);
  assign _0471_ = re ? _0470_ : _0468_;
  assign _0001_[3] = ~(_0471_ | rst);
  assign _0472_ = ~(we ^ head[0]);
  assign _0000_[0] = ~(_0472_ | rst);
  assign _0473_ = ~head[1];
  assign _0474_ = we ? _0265_ : _0473_;
  assign _0000_[1] = ~(_0474_ | rst);
  assign _0475_ = we ? _0270_ : _0272_;
  assign _0000_[2] = ~(_0475_ | rst);
  assign _0476_ = ~head[3];
  assign _0477_ = we ? _0274_ : _0476_;
  assign _0000_[3] = ~(_0477_ | rst);
  assign _0478_ = ~\mem[11] [0];
  assign _0479_ = _0422_ & ~(_0423_);
  assign _0480_ = ~(_0479_ & _0421_);
  assign _0481_ = ~(_0480_ | _0426_);
  assign _0482_ = _0481_ ? _0428_ : _0478_;
  assign _0483_ = _0270_ & ~(_0274_);
  assign _0484_ = ~(_0483_ & _0430_);
  assign _0485_ = ~(_0484_ | _0418_);
  assign _0022_ = ~(_0485_ | _0482_);
  assign _0486_ = ~\mem[11] [1];
  assign _0487_ = _0481_ ? _0435_ : _0486_;
  assign _0023_ = ~(_0487_ | _0485_);
  assign _0488_ = ~\mem[11] [2];
  assign _0489_ = _0481_ ? _0438_ : _0488_;
  assign _0024_ = ~(_0489_ | _0485_);
  assign _0490_ = ~\mem[11] [3];
  assign _0491_ = _0481_ ? _0441_ : _0490_;
  assign _0025_ = ~(_0491_ | _0485_);
  assign _0492_ = ~\mem[11] [4];
  assign _0493_ = _0481_ ? _0444_ : _0492_;
  assign _0026_ = ~(_0493_ | _0485_);
  assign _0494_ = ~\mem[11] [5];
  assign _0495_ = _0481_ ? _0447_ : _0494_;
  assign _0027_ = ~(_0495_ | _0485_);
  assign _0496_ = ~\mem[11] [6];
  assign _0497_ = _0481_ ? _0450_ : _0496_;
  assign _0028_ = ~(_0497_ | _0485_);
  assign _0498_ = ~\mem[11] [7];
  assign _0499_ = _0481_ ? _0453_ : _0498_;
  assign _0029_ = ~(_0499_ | _0485_);
  assign _0500_ = ~\mem[11] [8];
  assign _0501_ = _0481_ ? _0456_ : _0500_;
  assign _0030_ = ~(_0501_ | _0485_);
  assign _0502_ = ~\mem[11] [9];
  assign _0503_ = _0481_ ? _0459_ : _0502_;
  assign _0031_ = ~(_0503_ | _0485_);
  assign _0504_ = ~\mem[7] [0];
  assign _0505_ = ~(_0418_ | _0476_);
  assign _0506_ = ~(_0505_ | _0422_);
  assign _0507_ = ~(_0506_ & _0421_);
  assign _0508_ = ~(_0507_ | _0426_);
  assign _0509_ = _0508_ ? _0428_ : _0504_;
  assign _0510_ = ~(_0273_ ^ _0476_);
  assign _0511_ = ~(_0510_ | _0270_);
  assign _0512_ = ~(_0511_ & _0430_);
  assign _0513_ = ~(_0512_ | _0418_);
  assign _0132_ = ~(_0513_ | _0509_);
  assign _0514_ = ~\mem[7] [1];
  assign _0515_ = _0508_ ? _0435_ : _0514_;
  assign _0133_ = ~(_0515_ | _0513_);
  assign _0516_ = ~\mem[7] [2];
  assign _0517_ = _0508_ ? _0438_ : _0516_;
  assign _0134_ = ~(_0517_ | _0513_);
  assign _0518_ = ~\mem[7] [3];
  assign _0519_ = _0508_ ? _0441_ : _0518_;
  assign _0135_ = ~(_0519_ | _0513_);
  assign _0520_ = ~\mem[7] [4];
  assign _0521_ = _0508_ ? _0444_ : _0520_;
  assign _0136_ = ~(_0521_ | _0513_);
  assign _0522_ = ~\mem[7] [5];
  assign _0523_ = _0508_ ? _0447_ : _0522_;
  assign _0137_ = ~(_0523_ | _0513_);
  assign _0524_ = ~\mem[7] [6];
  assign _0525_ = _0508_ ? _0450_ : _0524_;
  assign _0138_ = ~(_0525_ | _0513_);
  assign _0526_ = ~\mem[7] [7];
  assign _0527_ = _0508_ ? _0453_ : _0526_;
  assign _0139_ = ~(_0527_ | _0513_);
  assign _0528_ = ~\mem[7] [8];
  assign _0529_ = _0508_ ? _0456_ : _0528_;
  assign _0140_ = ~(_0529_ | _0513_);
  assign _0530_ = ~\mem[7] [9];
  assign _0531_ = _0508_ ? _0459_ : _0530_;
  assign _0141_ = ~(_0531_ | _0513_);
  assign _0532_ = ~\mem[14] [0];
  assign _0533_ = _0420_ | ~(_0419_);
  assign _0534_ = _0533_ | ~(_0424_);
  assign _0535_ = ~(_0534_ | _0426_);
  assign _0536_ = _0535_ ? _0428_ : _0532_;
  assign _0537_ = head[1] | ~(head[0]);
  assign _0538_ = _0537_ | ~(_0431_);
  assign _0539_ = ~(_0538_ | _0418_);
  assign _0052_ = ~(_0539_ | _0536_);
  assign _0540_ = ~\mem[14] [1];
  assign _0541_ = _0535_ ? _0435_ : _0540_;
  assign _0053_ = ~(_0541_ | _0539_);
  assign _0542_ = ~\mem[14] [2];
  assign _0543_ = _0535_ ? _0438_ : _0542_;
  assign _0054_ = ~(_0543_ | _0539_);
  assign _0544_ = ~\mem[14] [3];
  assign _0545_ = _0535_ ? _0441_ : _0544_;
  assign _0055_ = ~(_0545_ | _0539_);
  assign _0546_ = ~\mem[14] [4];
  assign _0547_ = _0535_ ? _0444_ : _0546_;
  assign _0056_ = ~(_0547_ | _0539_);
  assign _0548_ = ~\mem[14] [5];
  assign _0549_ = _0535_ ? _0447_ : _0548_;
  assign _0057_ = ~(_0549_ | _0539_);
  assign _0550_ = ~\mem[14] [6];
  assign _0551_ = _0535_ ? _0450_ : _0550_;
  assign _0058_ = ~(_0551_ | _0539_);
  assign _0552_ = ~\mem[14] [7];
  assign _0553_ = _0535_ ? _0453_ : _0552_;
  assign _0059_ = ~(_0553_ | _0539_);
  assign _0554_ = ~\mem[14] [8];
  assign _0555_ = _0535_ ? _0456_ : _0554_;
  assign _0060_ = ~(_0555_ | _0539_);
  assign _0556_ = ~\mem[14] [9];
  assign _0557_ = _0535_ ? _0459_ : _0556_;
  assign _0061_ = ~(_0557_ | _0539_);
  assign _0558_ = ~\mem[0] [0];
  assign _0559_ = ~(_0418_ | _0473_);
  assign _0560_ = _0559_ | ~(_0419_);
  assign _0561_ = _0505_ | ~(_0422_);
  assign _0562_ = _0561_ | _0560_;
  assign _0563_ = ~(_0562_ | _0426_);
  assign _0564_ = _0563_ ? _0428_ : _0558_;
  assign _0565_ = ~(head[1] & head[0]);
  assign _0566_ = _0510_ | ~(_0270_);
  assign _0567_ = ~(_0566_ | _0565_);
  assign _0568_ = _0567_ & ~(_0418_);
  assign _0002_ = ~(_0568_ | _0564_);
  assign _0569_ = ~\mem[0] [1];
  assign _0570_ = _0563_ ? _0435_ : _0569_;
  assign _0003_ = ~(_0570_ | _0568_);
  assign _0571_ = ~\mem[0] [2];
  assign _0572_ = _0563_ ? _0438_ : _0571_;
  assign _0004_ = ~(_0572_ | _0568_);
  assign _0573_ = ~\mem[0] [3];
  assign _0574_ = _0563_ ? _0441_ : _0573_;
  assign _0005_ = ~(_0574_ | _0568_);
  assign _0575_ = ~\mem[0] [4];
  assign _0576_ = _0563_ ? _0444_ : _0575_;
  assign _0006_ = ~(_0576_ | _0568_);
  assign _0577_ = ~\mem[0] [5];
  assign _0578_ = _0563_ ? _0447_ : _0577_;
  assign _0007_ = ~(_0578_ | _0568_);
  assign _0579_ = ~\mem[0] [6];
  assign _0580_ = _0563_ ? _0450_ : _0579_;
  assign _0008_ = ~(_0580_ | _0568_);
  assign _0581_ = ~\mem[0] [7];
  assign _0582_ = _0563_ ? _0453_ : _0581_;
  assign _0009_ = ~(_0582_ | _0568_);
  assign _0583_ = ~\mem[0] [8];
  assign _0584_ = _0563_ ? _0456_ : _0583_;
  assign _0010_ = ~(_0584_ | _0568_);
  assign _0585_ = ~\mem[0] [9];
  assign _0586_ = _0563_ ? _0459_ : _0585_;
  assign _0011_ = ~(_0586_ | _0568_);
  assign _0587_ = ~\mem[6] [0];
  assign _0588_ = _0533_ | ~(_0506_);
  assign _0589_ = ~(_0588_ | _0426_);
  assign _0590_ = _0589_ ? _0428_ : _0587_;
  assign _0591_ = _0537_ | ~(_0511_);
  assign _0592_ = ~(_0591_ | _0418_);
  assign _0122_ = ~(_0592_ | _0590_);
  assign _0593_ = ~\mem[6] [1];
  assign _0594_ = _0589_ ? _0435_ : _0593_;
  assign _0123_ = ~(_0594_ | _0592_);
  assign _0595_ = ~\mem[6] [2];
  assign _0596_ = _0589_ ? _0438_ : _0595_;
  assign _0124_ = ~(_0596_ | _0592_);
  assign _0597_ = ~\mem[6] [3];
  assign _0598_ = _0589_ ? _0441_ : _0597_;
  assign _0125_ = ~(_0598_ | _0592_);
  assign _0599_ = ~\mem[6] [4];
  assign _0600_ = _0589_ ? _0444_ : _0599_;
  assign _0126_ = ~(_0600_ | _0592_);
  assign _0601_ = ~\mem[6] [5];
  assign _0602_ = _0589_ ? _0447_ : _0601_;
  assign _0127_ = ~(_0602_ | _0592_);
  assign _0603_ = ~\mem[6] [6];
  assign _0604_ = _0589_ ? _0450_ : _0603_;
  assign _0128_ = ~(_0604_ | _0592_);
  assign _0605_ = ~\mem[6] [7];
  assign _0606_ = _0589_ ? _0453_ : _0605_;
  assign _0129_ = ~(_0606_ | _0592_);
  assign _0607_ = ~\mem[6] [8];
  assign _0608_ = _0589_ ? _0456_ : _0607_;
  assign _0130_ = ~(_0608_ | _0592_);
  assign _0609_ = ~\mem[6] [9];
  assign _0610_ = _0589_ ? _0459_ : _0609_;
  assign _0131_ = ~(_0610_ | _0592_);
  assign _0611_ = ~\mem[13] [0];
  assign _0612_ = _0559_ | _0419_;
  assign _0613_ = _0612_ | ~(_0424_);
  assign _0614_ = ~(_0613_ | _0426_);
  assign _0615_ = _0614_ ? _0428_ : _0611_;
  assign _0616_ = head[1] | head[0];
  assign _0617_ = _0616_ | ~(_0431_);
  assign _0618_ = ~(_0617_ | _0418_);
  assign _0042_ = ~(_0618_ | _0615_);
  assign _0619_ = ~\mem[13] [1];
  assign _0620_ = _0614_ ? _0435_ : _0619_;
  assign _0043_ = ~(_0620_ | _0618_);
  assign _0621_ = ~\mem[13] [2];
  assign _0622_ = _0614_ ? _0438_ : _0621_;
  assign _0044_ = ~(_0622_ | _0618_);
  assign _0623_ = ~\mem[13] [3];
  assign _0624_ = _0614_ ? _0441_ : _0623_;
  assign _0045_ = ~(_0624_ | _0618_);
  assign _0625_ = ~\mem[13] [4];
  assign _0626_ = _0614_ ? _0444_ : _0625_;
  assign _0046_ = ~(_0626_ | _0618_);
  assign _0627_ = ~\mem[13] [5];
  assign _0628_ = _0614_ ? _0447_ : _0627_;
  assign _0047_ = ~(_0628_ | _0618_);
  assign _0629_ = ~\mem[13] [6];
  assign _0630_ = _0614_ ? _0450_ : _0629_;
  assign _0048_ = ~(_0630_ | _0618_);
  assign _0631_ = ~\mem[13] [7];
  assign _0632_ = _0614_ ? _0453_ : _0631_;
  assign _0049_ = ~(_0632_ | _0618_);
  assign _0633_ = ~\mem[13] [8];
  assign _0634_ = _0614_ ? _0456_ : _0633_;
  assign _0050_ = ~(_0634_ | _0618_);
  assign _0635_ = ~\mem[13] [9];
  assign _0636_ = _0614_ ? _0459_ : _0635_;
  assign _0051_ = ~(_0636_ | _0618_);
  assign _0637_ = ~\mem[1] [0];
  assign _0638_ = _0612_ | _0561_;
  assign _0639_ = ~(_0638_ | _0426_);
  assign _0640_ = _0639_ ? _0428_ : _0637_;
  assign _0641_ = _0616_ | _0566_;
  assign _0642_ = ~(_0641_ | _0418_);
  assign _0072_ = ~(_0642_ | _0640_);
  assign _0643_ = ~\mem[1] [1];
  assign _0644_ = _0639_ ? _0435_ : _0643_;
  assign _0073_ = ~(_0644_ | _0642_);
  assign _0645_ = ~\mem[1] [2];
  assign _0646_ = _0639_ ? _0438_ : _0645_;
  assign _0074_ = ~(_0646_ | _0642_);
  assign _0647_ = ~\mem[1] [3];
  assign _0648_ = _0639_ ? _0441_ : _0647_;
  assign _0075_ = ~(_0648_ | _0642_);
  assign _0649_ = ~\mem[1] [4];
  assign _0650_ = _0639_ ? _0444_ : _0649_;
  assign _0076_ = ~(_0650_ | _0642_);
  assign _0651_ = ~\mem[1] [5];
  assign _0652_ = _0639_ ? _0447_ : _0651_;
  assign _0077_ = ~(_0652_ | _0642_);
  assign _0653_ = ~\mem[1] [6];
  assign _0654_ = _0639_ ? _0450_ : _0653_;
  assign _0078_ = ~(_0654_ | _0642_);
  assign _0655_ = ~\mem[1] [7];
  assign _0656_ = _0639_ ? _0453_ : _0655_;
  assign _0079_ = ~(_0656_ | _0642_);
  assign _0657_ = ~\mem[1] [8];
  assign _0658_ = _0639_ ? _0456_ : _0657_;
  assign _0080_ = ~(_0658_ | _0642_);
  assign _0659_ = ~\mem[1] [9];
  assign _0660_ = _0639_ ? _0459_ : _0659_;
  assign _0081_ = ~(_0660_ | _0642_);
  assign _0661_ = ~\mem[12] [0];
  assign _0662_ = _0560_ | ~(_0424_);
  assign _0663_ = ~(_0662_ | _0426_);
  assign _0664_ = _0663_ ? _0428_ : _0661_;
  assign _0665_ = _0565_ | ~(_0431_);
  assign _0666_ = ~(_0665_ | _0418_);
  assign _0032_ = ~(_0666_ | _0664_);
  assign _0667_ = ~\mem[12] [1];
  assign _0668_ = _0663_ ? _0435_ : _0667_;
  assign _0033_ = ~(_0668_ | _0666_);
  assign _0669_ = ~\mem[12] [2];
  assign _0670_ = _0663_ ? _0438_ : _0669_;
  assign _0034_ = ~(_0670_ | _0666_);
  assign _0671_ = ~\mem[12] [3];
  assign _0672_ = _0663_ ? _0441_ : _0671_;
  assign _0035_ = ~(_0672_ | _0666_);
  assign _0673_ = ~\mem[12] [4];
  assign _0674_ = _0663_ ? _0444_ : _0673_;
  assign _0036_ = ~(_0674_ | _0666_);
  assign _0675_ = ~\mem[12] [5];
  assign _0676_ = _0663_ ? _0447_ : _0675_;
  assign _0037_ = ~(_0676_ | _0666_);
  assign _0677_ = ~\mem[12] [6];
  assign _0678_ = _0663_ ? _0450_ : _0677_;
  assign _0038_ = ~(_0678_ | _0666_);
  assign _0679_ = ~\mem[12] [7];
  assign _0680_ = _0663_ ? _0453_ : _0679_;
  assign _0039_ = ~(_0680_ | _0666_);
  assign _0681_ = ~\mem[12] [8];
  assign _0682_ = _0663_ ? _0456_ : _0681_;
  assign _0040_ = ~(_0682_ | _0666_);
  assign _0683_ = ~\mem[12] [9];
  assign _0684_ = _0663_ ? _0459_ : _0683_;
  assign _0041_ = ~(_0684_ | _0666_);
  assign _0685_ = ~\mem[2] [0];
  assign _0686_ = _0561_ | _0533_;
  assign _0687_ = ~(_0686_ | _0426_);
  assign _0688_ = _0687_ ? _0428_ : _0685_;
  assign _0689_ = _0566_ | _0537_;
  assign _0690_ = ~(_0689_ | _0418_);
  assign _0082_ = ~(_0690_ | _0688_);
  assign _0691_ = ~\mem[2] [1];
  assign _0692_ = _0687_ ? _0435_ : _0691_;
  assign _0083_ = ~(_0692_ | _0690_);
  assign _0693_ = ~\mem[2] [2];
  assign _0694_ = _0687_ ? _0438_ : _0693_;
  assign _0084_ = ~(_0694_ | _0690_);
  assign _0695_ = ~\mem[2] [3];
  assign _0696_ = _0687_ ? _0441_ : _0695_;
  assign _0085_ = ~(_0696_ | _0690_);
  assign _0697_ = ~\mem[2] [4];
  assign _0698_ = _0687_ ? _0444_ : _0697_;
  assign _0086_ = ~(_0698_ | _0690_);
  assign _0699_ = ~\mem[2] [5];
  assign _0700_ = _0687_ ? _0447_ : _0699_;
  assign _0087_ = ~(_0700_ | _0690_);
  assign _0701_ = ~\mem[2] [6];
  assign _0702_ = _0687_ ? _0450_ : _0701_;
  assign _0088_ = ~(_0702_ | _0690_);
  assign _0703_ = ~\mem[2] [7];
  assign _0704_ = _0687_ ? _0453_ : _0703_;
  assign _0089_ = ~(_0704_ | _0690_);
  assign _0705_ = ~\mem[2] [8];
  assign _0706_ = _0687_ ? _0456_ : _0705_;
  assign _0090_ = ~(_0706_ | _0690_);
  assign _0707_ = ~\mem[2] [9];
  assign _0708_ = _0687_ ? _0459_ : _0707_;
  assign _0091_ = ~(_0708_ | _0690_);
  assign _0709_ = ~\mem[10] [0];
  assign _0710_ = _0533_ | ~(_0479_);
  assign _0711_ = ~(_0710_ | _0426_);
  assign _0712_ = _0711_ ? _0428_ : _0709_;
  assign _0713_ = _0537_ | ~(_0483_);
  assign _0714_ = ~(_0713_ | _0418_);
  assign _0012_ = ~(_0714_ | _0712_);
  assign _0715_ = ~\mem[10] [1];
  assign _0716_ = _0711_ ? _0435_ : _0715_;
  assign _0013_ = ~(_0716_ | _0714_);
  assign _0717_ = ~\mem[10] [2];
  assign _0718_ = _0711_ ? _0438_ : _0717_;
  assign _0014_ = ~(_0718_ | _0714_);
  assign _0719_ = ~\mem[10] [3];
  assign _0720_ = _0711_ ? _0441_ : _0719_;
  assign _0015_ = ~(_0720_ | _0714_);
  assign _0721_ = ~\mem[10] [4];
  assign _0722_ = _0711_ ? _0444_ : _0721_;
  assign _0016_ = ~(_0722_ | _0714_);
  assign _0723_ = ~\mem[10] [5];
  assign _0724_ = _0711_ ? _0447_ : _0723_;
  assign _0017_ = ~(_0724_ | _0714_);
  assign _0725_ = ~\mem[10] [6];
  assign _0726_ = _0711_ ? _0450_ : _0725_;
  assign _0018_ = ~(_0726_ | _0714_);
  assign _0727_ = ~\mem[10] [7];
  assign _0728_ = _0711_ ? _0453_ : _0727_;
  assign _0019_ = ~(_0728_ | _0714_);
  assign _0729_ = ~\mem[10] [8];
  assign _0730_ = _0711_ ? _0456_ : _0729_;
  assign _0020_ = ~(_0730_ | _0714_);
  assign _0731_ = ~\mem[10] [9];
  assign _0732_ = _0711_ ? _0459_ : _0731_;
  assign _0021_ = ~(_0732_ | _0714_);
  assign _0733_ = ~\mem[3] [0];
  assign _0734_ = _0561_ | ~(_0421_);
  assign _0735_ = ~(_0734_ | _0426_);
  assign _0736_ = _0735_ ? _0428_ : _0733_;
  assign _0737_ = _0566_ | ~(_0430_);
  assign _0738_ = ~(_0737_ | _0418_);
  assign _0092_ = ~(_0738_ | _0736_);
  assign _0739_ = ~\mem[3] [1];
  assign _0740_ = _0735_ ? _0435_ : _0739_;
  assign _0093_ = ~(_0740_ | _0738_);
  assign _0741_ = ~\mem[3] [2];
  assign _0742_ = _0735_ ? _0438_ : _0741_;
  assign _0094_ = ~(_0742_ | _0738_);
  assign _0743_ = ~\mem[3] [3];
  assign _0744_ = _0735_ ? _0441_ : _0743_;
  assign _0095_ = ~(_0744_ | _0738_);
  assign _0745_ = ~\mem[3] [4];
  assign _0746_ = _0735_ ? _0444_ : _0745_;
  assign _0096_ = ~(_0746_ | _0738_);
  assign _0747_ = ~\mem[3] [5];
  assign _0748_ = _0735_ ? _0447_ : _0747_;
  assign _0097_ = ~(_0748_ | _0738_);
  assign _0749_ = ~\mem[3] [6];
  assign _0750_ = _0735_ ? _0450_ : _0749_;
  assign _0098_ = ~(_0750_ | _0738_);
  assign _0751_ = ~\mem[3] [7];
  assign _0752_ = _0735_ ? _0453_ : _0751_;
  assign _0099_ = ~(_0752_ | _0738_);
  assign _0753_ = ~\mem[3] [8];
  assign _0754_ = _0735_ ? _0456_ : _0753_;
  assign _0100_ = ~(_0754_ | _0738_);
  assign _0755_ = ~\mem[3] [9];
  assign _0756_ = _0735_ ? _0459_ : _0755_;
  assign _0101_ = ~(_0756_ | _0738_);
  assign _0162_ = ~\mem[9] [0];
  assign _0163_ = _0612_ | ~(_0479_);
  assign _0164_ = ~(_0163_ | _0426_);
  assign _0165_ = _0164_ ? _0428_ : _0162_;
  assign _0166_ = _0616_ | ~(_0483_);
  assign _0167_ = ~(_0166_ | _0418_);
  assign _0152_ = ~(_0167_ | _0165_);
  assign _0168_ = ~\mem[9] [1];
  assign _0169_ = _0164_ ? _0435_ : _0168_;
  assign _0153_ = ~(_0169_ | _0167_);
  assign _0170_ = ~\mem[9] [2];
  assign _0171_ = _0164_ ? _0438_ : _0170_;
  assign _0154_ = ~(_0171_ | _0167_);
  assign _0172_ = ~\mem[9] [3];
  assign _0173_ = _0164_ ? _0441_ : _0172_;
  assign _0155_ = ~(_0173_ | _0167_);
  assign _0174_ = ~\mem[9] [4];
  assign _0175_ = _0164_ ? _0444_ : _0174_;
  assign _0156_ = ~(_0175_ | _0167_);
  assign _0176_ = ~\mem[9] [5];
  assign _0177_ = _0164_ ? _0447_ : _0176_;
  assign _0157_ = ~(_0177_ | _0167_);
  assign _0178_ = ~\mem[9] [6];
  assign _0179_ = _0164_ ? _0450_ : _0178_;
  assign _0158_ = ~(_0179_ | _0167_);
  assign _0180_ = ~\mem[9] [7];
  assign _0181_ = _0164_ ? _0453_ : _0180_;
  assign _0159_ = ~(_0181_ | _0167_);
  assign _0182_ = ~\mem[9] [8];
  assign _0183_ = _0164_ ? _0456_ : _0182_;
  assign _0160_ = ~(_0183_ | _0167_);
  assign _0184_ = ~\mem[9] [9];
  assign _0185_ = _0164_ ? _0459_ : _0184_;
  assign _0161_ = ~(_0185_ | _0167_);
  assign _0186_ = ~\mem[4] [0];
  assign _0187_ = _0560_ | ~(_0506_);
  assign _0188_ = ~(_0187_ | _0426_);
  assign _0189_ = _0188_ ? _0428_ : _0186_;
  assign _0190_ = _0565_ | ~(_0511_);
  assign _0191_ = ~(_0190_ | _0418_);
  assign _0102_ = ~(_0191_ | _0189_);
  assign _0192_ = ~\mem[4] [1];
  assign _0193_ = _0188_ ? _0435_ : _0192_;
  assign _0103_ = ~(_0193_ | _0191_);
  assign _0194_ = ~\mem[4] [2];
  assign _0195_ = _0188_ ? _0438_ : _0194_;
  assign _0104_ = ~(_0195_ | _0191_);
  assign _0196_ = ~\mem[4] [3];
  assign _0197_ = _0188_ ? _0441_ : _0196_;
  assign _0105_ = ~(_0197_ | _0191_);
  assign _0198_ = ~\mem[4] [4];
  assign _0199_ = _0188_ ? _0444_ : _0198_;
  assign _0106_ = ~(_0199_ | _0191_);
  assign _0200_ = ~\mem[4] [5];
  assign _0201_ = _0188_ ? _0447_ : _0200_;
  assign _0107_ = ~(_0201_ | _0191_);
  assign _0202_ = ~\mem[4] [6];
  assign _0203_ = _0188_ ? _0450_ : _0202_;
  assign _0108_ = ~(_0203_ | _0191_);
  assign _0204_ = ~\mem[4] [7];
  assign _0205_ = _0188_ ? _0453_ : _0204_;
  assign _0109_ = ~(_0205_ | _0191_);
  assign _0206_ = ~\mem[4] [8];
  assign _0207_ = _0188_ ? _0456_ : _0206_;
  assign _0110_ = ~(_0207_ | _0191_);
  assign _0208_ = ~\mem[4] [9];
  assign _0209_ = _0188_ ? _0459_ : _0208_;
  assign _0111_ = ~(_0209_ | _0191_);
  assign _0210_ = ~\mem[5] [0];
  assign _0211_ = _0612_ | ~(_0506_);
  assign _0212_ = ~(_0211_ | _0426_);
  assign _0213_ = _0212_ ? _0428_ : _0210_;
  assign _0214_ = _0616_ | ~(_0511_);
  assign _0215_ = ~(_0214_ | _0418_);
  assign _0112_ = ~(_0215_ | _0213_);
  assign _0216_ = ~\mem[5] [1];
  assign _0217_ = _0212_ ? _0435_ : _0216_;
  assign _0113_ = ~(_0217_ | _0215_);
  assign _0218_ = ~\mem[5] [2];
  assign _0219_ = _0212_ ? _0438_ : _0218_;
  assign _0114_ = ~(_0219_ | _0215_);
  assign _0220_ = ~\mem[5] [3];
  assign _0221_ = _0212_ ? _0441_ : _0220_;
  assign _0115_ = ~(_0221_ | _0215_);
  assign _0222_ = ~\mem[5] [4];
  assign _0223_ = _0212_ ? _0444_ : _0222_;
  assign _0116_ = ~(_0223_ | _0215_);
  assign _0224_ = ~\mem[5] [5];
  assign _0225_ = _0212_ ? _0447_ : _0224_;
  assign _0117_ = ~(_0225_ | _0215_);
  assign _0226_ = ~\mem[5] [6];
  assign _0227_ = _0212_ ? _0450_ : _0226_;
  assign _0118_ = ~(_0227_ | _0215_);
  assign _0228_ = ~\mem[5] [7];
  assign _0229_ = _0212_ ? _0453_ : _0228_;
  assign _0119_ = ~(_0229_ | _0215_);
  assign _0230_ = ~\mem[5] [8];
  assign _0231_ = _0212_ ? _0456_ : _0230_;
  assign _0120_ = ~(_0231_ | _0215_);
  assign _0232_ = ~\mem[5] [9];
  assign _0233_ = _0212_ ? _0459_ : _0232_;
  assign _0121_ = ~(_0233_ | _0215_);
  assign _0234_ = ~\mem[8] [0];
  assign _0235_ = _0560_ | ~(_0479_);
  assign _0236_ = ~(_0235_ | _0426_);
  assign _0237_ = _0236_ ? _0428_ : _0234_;
  assign _0238_ = _0565_ | ~(_0483_);
  assign _0239_ = ~(_0238_ | _0418_);
  assign _0142_ = ~(_0239_ | _0237_);
  assign _0240_ = ~\mem[8] [1];
  assign _0241_ = _0236_ ? _0435_ : _0240_;
  assign _0143_ = ~(_0241_ | _0239_);
  assign _0242_ = ~\mem[8] [2];
  assign _0243_ = _0236_ ? _0438_ : _0242_;
  assign _0144_ = ~(_0243_ | _0239_);
  assign _0244_ = ~\mem[8] [3];
  assign _0245_ = _0236_ ? _0441_ : _0244_;
  assign _0145_ = ~(_0245_ | _0239_);
  assign _0246_ = ~\mem[8] [4];
  assign _0247_ = _0236_ ? _0444_ : _0246_;
  assign _0146_ = ~(_0247_ | _0239_);
  assign _0248_ = ~\mem[8] [5];
  assign _0249_ = _0236_ ? _0447_ : _0248_;
  assign _0147_ = ~(_0249_ | _0239_);
  assign _0250_ = ~\mem[8] [6];
  assign _0251_ = _0236_ ? _0450_ : _0250_;
  assign _0148_ = ~(_0251_ | _0239_);
  assign _0252_ = ~\mem[8] [7];
  assign _0253_ = _0236_ ? _0453_ : _0252_;
  assign _0149_ = ~(_0253_ | _0239_);
  assign _0254_ = ~\mem[8] [8];
  assign _0255_ = _0236_ ? _0456_ : _0254_;
  assign _0150_ = ~(_0255_ | _0239_);
  assign _0256_ = ~\mem[8] [9];
  assign _0257_ = _0236_ ? _0459_ : _0256_;
  assign _0151_ = ~(_0257_ | _0239_);
  always @(posedge clk)
      \mem[4] [0] <= _0102_;
  always @(posedge clk)
      \mem[4] [1] <= _0103_;
  always @(posedge clk)
      \mem[4] [2] <= _0104_;
  always @(posedge clk)
      \mem[4] [3] <= _0105_;
  always @(posedge clk)
      \mem[4] [4] <= _0106_;
  always @(posedge clk)
      \mem[4] [5] <= _0107_;
  always @(posedge clk)
      \mem[4] [6] <= _0108_;
  always @(posedge clk)
      \mem[4] [7] <= _0109_;
  always @(posedge clk)
      \mem[4] [8] <= _0110_;
  always @(posedge clk)
      \mem[4] [9] <= _0111_;
  always @(posedge clk)
      \mem[5] [0] <= _0112_;
  always @(posedge clk)
      \mem[5] [1] <= _0113_;
  always @(posedge clk)
      \mem[5] [2] <= _0114_;
  always @(posedge clk)
      \mem[5] [3] <= _0115_;
  always @(posedge clk)
      \mem[5] [4] <= _0116_;
  always @(posedge clk)
      \mem[5] [5] <= _0117_;
  always @(posedge clk)
      \mem[5] [6] <= _0118_;
  always @(posedge clk)
      \mem[5] [7] <= _0119_;
  always @(posedge clk)
      \mem[5] [8] <= _0120_;
  always @(posedge clk)
      \mem[5] [9] <= _0121_;
  always @(posedge clk)
      \mem[14] [0] <= _0052_;
  always @(posedge clk)
      \mem[14] [1] <= _0053_;
  always @(posedge clk)
      \mem[14] [2] <= _0054_;
  always @(posedge clk)
      \mem[14] [3] <= _0055_;
  always @(posedge clk)
      \mem[14] [4] <= _0056_;
  always @(posedge clk)
      \mem[14] [5] <= _0057_;
  always @(posedge clk)
      \mem[14] [6] <= _0058_;
  always @(posedge clk)
      \mem[14] [7] <= _0059_;
  always @(posedge clk)
      \mem[14] [8] <= _0060_;
  always @(posedge clk)
      \mem[14] [9] <= _0061_;
  always @(posedge clk)
      tail[0] <= _0001_[0];
  always @(posedge clk)
      tail[1] <= _0001_[1];
  always @(posedge clk)
      tail[2] <= _0001_[2];
  always @(posedge clk)
      tail[3] <= _0001_[3];
  always @(posedge clk)
      \mem[3] [0] <= _0092_;
  always @(posedge clk)
      \mem[3] [1] <= _0093_;
  always @(posedge clk)
      \mem[3] [2] <= _0094_;
  always @(posedge clk)
      \mem[3] [3] <= _0095_;
  always @(posedge clk)
      \mem[3] [4] <= _0096_;
  always @(posedge clk)
      \mem[3] [5] <= _0097_;
  always @(posedge clk)
      \mem[3] [6] <= _0098_;
  always @(posedge clk)
      \mem[3] [7] <= _0099_;
  always @(posedge clk)
      \mem[3] [8] <= _0100_;
  always @(posedge clk)
      \mem[3] [9] <= _0101_;
  always @(posedge clk)
      \mem[10] [0] <= _0012_;
  always @(posedge clk)
      \mem[10] [1] <= _0013_;
  always @(posedge clk)
      \mem[10] [2] <= _0014_;
  always @(posedge clk)
      \mem[10] [3] <= _0015_;
  always @(posedge clk)
      \mem[10] [4] <= _0016_;
  always @(posedge clk)
      \mem[10] [5] <= _0017_;
  always @(posedge clk)
      \mem[10] [6] <= _0018_;
  always @(posedge clk)
      \mem[10] [7] <= _0019_;
  always @(posedge clk)
      \mem[10] [8] <= _0020_;
  always @(posedge clk)
      \mem[10] [9] <= _0021_;
  always @(posedge clk)
      \mem[0] [0] <= _0002_;
  always @(posedge clk)
      \mem[0] [1] <= _0003_;
  always @(posedge clk)
      \mem[0] [2] <= _0004_;
  always @(posedge clk)
      \mem[0] [3] <= _0005_;
  always @(posedge clk)
      \mem[0] [4] <= _0006_;
  always @(posedge clk)
      \mem[0] [5] <= _0007_;
  always @(posedge clk)
      \mem[0] [6] <= _0008_;
  always @(posedge clk)
      \mem[0] [7] <= _0009_;
  always @(posedge clk)
      \mem[0] [8] <= _0010_;
  always @(posedge clk)
      \mem[0] [9] <= _0011_;
  always @(posedge clk)
      \mem[11] [0] <= _0022_;
  always @(posedge clk)
      \mem[11] [1] <= _0023_;
  always @(posedge clk)
      \mem[11] [2] <= _0024_;
  always @(posedge clk)
      \mem[11] [3] <= _0025_;
  always @(posedge clk)
      \mem[11] [4] <= _0026_;
  always @(posedge clk)
      \mem[11] [5] <= _0027_;
  always @(posedge clk)
      \mem[11] [6] <= _0028_;
  always @(posedge clk)
      \mem[11] [7] <= _0029_;
  always @(posedge clk)
      \mem[11] [8] <= _0030_;
  always @(posedge clk)
      \mem[11] [9] <= _0031_;
  always @(posedge clk)
      \mem[2] [0] <= _0082_;
  always @(posedge clk)
      \mem[2] [1] <= _0083_;
  always @(posedge clk)
      \mem[2] [2] <= _0084_;
  always @(posedge clk)
      \mem[2] [3] <= _0085_;
  always @(posedge clk)
      \mem[2] [4] <= _0086_;
  always @(posedge clk)
      \mem[2] [5] <= _0087_;
  always @(posedge clk)
      \mem[2] [6] <= _0088_;
  always @(posedge clk)
      \mem[2] [7] <= _0089_;
  always @(posedge clk)
      \mem[2] [8] <= _0090_;
  always @(posedge clk)
      \mem[2] [9] <= _0091_;
  always @(posedge clk)
      \mem[13] [0] <= _0042_;
  always @(posedge clk)
      \mem[13] [1] <= _0043_;
  always @(posedge clk)
      \mem[13] [2] <= _0044_;
  always @(posedge clk)
      \mem[13] [3] <= _0045_;
  always @(posedge clk)
      \mem[13] [4] <= _0046_;
  always @(posedge clk)
      \mem[13] [5] <= _0047_;
  always @(posedge clk)
      \mem[13] [6] <= _0048_;
  always @(posedge clk)
      \mem[13] [7] <= _0049_;
  always @(posedge clk)
      \mem[13] [8] <= _0050_;
  always @(posedge clk)
      \mem[13] [9] <= _0051_;
  always @(posedge clk)
      \mem[1] [0] <= _0072_;
  always @(posedge clk)
      \mem[1] [1] <= _0073_;
  always @(posedge clk)
      \mem[1] [2] <= _0074_;
  always @(posedge clk)
      \mem[1] [3] <= _0075_;
  always @(posedge clk)
      \mem[1] [4] <= _0076_;
  always @(posedge clk)
      \mem[1] [5] <= _0077_;
  always @(posedge clk)
      \mem[1] [6] <= _0078_;
  always @(posedge clk)
      \mem[1] [7] <= _0079_;
  always @(posedge clk)
      \mem[1] [8] <= _0080_;
  always @(posedge clk)
      \mem[1] [9] <= _0081_;
  always @(posedge clk)
      \mem[6] [0] <= _0122_;
  always @(posedge clk)
      \mem[6] [1] <= _0123_;
  always @(posedge clk)
      \mem[6] [2] <= _0124_;
  always @(posedge clk)
      \mem[6] [3] <= _0125_;
  always @(posedge clk)
      \mem[6] [4] <= _0126_;
  always @(posedge clk)
      \mem[6] [5] <= _0127_;
  always @(posedge clk)
      \mem[6] [6] <= _0128_;
  always @(posedge clk)
      \mem[6] [7] <= _0129_;
  always @(posedge clk)
      \mem[6] [8] <= _0130_;
  always @(posedge clk)
      \mem[6] [9] <= _0131_;
  always @(posedge clk)
      \mem[15] [0] <= _0062_;
  always @(posedge clk)
      \mem[15] [1] <= _0063_;
  always @(posedge clk)
      \mem[15] [2] <= _0064_;
  always @(posedge clk)
      \mem[15] [3] <= _0065_;
  always @(posedge clk)
      \mem[15] [4] <= _0066_;
  always @(posedge clk)
      \mem[15] [5] <= _0067_;
  always @(posedge clk)
      \mem[15] [6] <= _0068_;
  always @(posedge clk)
      \mem[15] [7] <= _0069_;
  always @(posedge clk)
      \mem[15] [8] <= _0070_;
  always @(posedge clk)
      \mem[15] [9] <= _0071_;
  always @(posedge clk)
      \mem[9] [0] <= _0152_;
  always @(posedge clk)
      \mem[9] [1] <= _0153_;
  always @(posedge clk)
      \mem[9] [2] <= _0154_;
  always @(posedge clk)
      \mem[9] [3] <= _0155_;
  always @(posedge clk)
      \mem[9] [4] <= _0156_;
  always @(posedge clk)
      \mem[9] [5] <= _0157_;
  always @(posedge clk)
      \mem[9] [6] <= _0158_;
  always @(posedge clk)
      \mem[9] [7] <= _0159_;
  always @(posedge clk)
      \mem[9] [8] <= _0160_;
  always @(posedge clk)
      \mem[9] [9] <= _0161_;
  always @(posedge clk)
      \mem[8] [0] <= _0142_;
  always @(posedge clk)
      \mem[8] [1] <= _0143_;
  always @(posedge clk)
      \mem[8] [2] <= _0144_;
  always @(posedge clk)
      \mem[8] [3] <= _0145_;
  always @(posedge clk)
      \mem[8] [4] <= _0146_;
  always @(posedge clk)
      \mem[8] [5] <= _0147_;
  always @(posedge clk)
      \mem[8] [6] <= _0148_;
  always @(posedge clk)
      \mem[8] [7] <= _0149_;
  always @(posedge clk)
      \mem[8] [8] <= _0150_;
  always @(posedge clk)
      \mem[8] [9] <= _0151_;
  always @(posedge clk)
      \mem[12] [0] <= _0032_;
  always @(posedge clk)
      \mem[12] [1] <= _0033_;
  always @(posedge clk)
      \mem[12] [2] <= _0034_;
  always @(posedge clk)
      \mem[12] [3] <= _0035_;
  always @(posedge clk)
      \mem[12] [4] <= _0036_;
  always @(posedge clk)
      \mem[12] [5] <= _0037_;
  always @(posedge clk)
      \mem[12] [6] <= _0038_;
  always @(posedge clk)
      \mem[12] [7] <= _0039_;
  always @(posedge clk)
      \mem[12] [8] <= _0040_;
  always @(posedge clk)
      \mem[12] [9] <= _0041_;
  always @(posedge clk)
      \mem[7] [0] <= _0132_;
  always @(posedge clk)
      \mem[7] [1] <= _0133_;
  always @(posedge clk)
      \mem[7] [2] <= _0134_;
  always @(posedge clk)
      \mem[7] [3] <= _0135_;
  always @(posedge clk)
      \mem[7] [4] <= _0136_;
  always @(posedge clk)
      \mem[7] [5] <= _0137_;
  always @(posedge clk)
      \mem[7] [6] <= _0138_;
  always @(posedge clk)
      \mem[7] [7] <= _0139_;
  always @(posedge clk)
      \mem[7] [8] <= _0140_;
  always @(posedge clk)
      \mem[7] [9] <= _0141_;
  (* src = "fifo.v:16" *)
  always @(posedge clk)
      head[0] <= _0000_[0];
  (* src = "fifo.v:16" *)
  always @(posedge clk)
      head[1] <= _0000_[1];
  (* src = "fifo.v:16" *)
  always @(posedge clk)
      head[2] <= _0000_[2];
  (* src = "fifo.v:16" *)
  always @(posedge clk)
      head[3] <= _0000_[3];
endmodule

(* src = "ib.v:5" *)
module ib(clk, rst, ack, pkti, pkto, full, req);
  (* src = "ib.v:6" *)
  input ack;
  (* src = "ib.v:5" *)
  input clk;
  (* src = "ib.v:15" *)
  wire empty;
  (* src = "ib.v:9" *)
  output full;
  (* src = "ib.v:7" *)
  input [9:0] pkti;
  (* src = "ib.v:8" *)
  output [9:0] pkto;
  (* src = "ib.v:15" *)
  wire re;
  (* src = "ib.v:10" *)
  output [3:0] req;
  (* src = "ib.v:12" *)
  wire [3:0] reqi;
  (* src = "ib.v:5" *)
  input rst;
  (* src = "ib.v:14" *)
  wire we;
  (* module_not_derived = 32'd1 *)
  (* src = "ib.v:15" *)
  fifo fifo (
    .clk(clk),
    .empty(empty),
    .full(full),
    .pkti(pkti),
    .pkto(pkto),
    .re(re),
    .rst(rst),
    .we(we)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "ib.v:16" *)
  ibsm ibsm (
    .ack(ack),
    .clk(clk),
    .empty(empty),
    .pkto(pkto),
    .re(re),
    .req(req),
    .reqi(reqi),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "ib.v:17" *)
  mkreq mkreq (
    .clk(clk),
    .pkto(pkto),
    .reqi(reqi),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "ib.v:14" *)
  mkwe mkwe (
    .pkti(pkti),
    .we(we)
  );
endmodule

(* src = "ibsm.v:4" *)
module ibsm(clk, rst, ack, pkto, reqi, empty, re, req);
  (* src = "ibsm.v:15" *)
  wire [3:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  (* src = "ibsm.v:5" *)
  input ack;
  (* src = "ibsm.v:4" *)
  input clk;
  (* src = "ibsm.v:8" *)
  input empty;
  (* src = "ibsm.v:6" *)
  input [9:0] pkto;
  (* src = "ibsm.v:9" *)
  output re;
  (* src = "ibsm.v:10" *)
  output [3:0] req;
  (* src = "ibsm.v:7" *)
  input [3:0] reqi;
  (* src = "ibsm.v:4" *)
  input rst;
  (* onehot = 32'd1 *)
  reg [2:0] state;
  (* src = "ibsm.v:13" *)
  reg [3:0] tmp;
  assign _004_ = ~state[2];
  assign _005_ = ~state[0];
  assign _006_ = ack | rst;
  assign _007_ = empty | rst;
  assign _003_ = ~((_006_ | _004_) & (_005_ | _007_));
  assign _008_ = ~state[1];
  assign _009_ = ~rst;
  assign _010_ = pkto[9] & pkto[8];
  assign _011_ = _010_ | ~(_009_);
  assign _012_ = rst | ~(ack);
  assign _002_ = ~((_011_ | _008_) & (_004_ | _012_));
  assign _013_ = ~(_010_ & _009_);
  assign _014_ = rst | ~(empty);
  assign _015_ = ~((_013_ | _008_) & (_005_ | _014_));
  assign _001_ = _015_ | ~(_009_);
  assign _016_ = tmp[0] & ~(state[0]);
  assign _017_ = pkto[8] | ~(pkto[9]);
  assign _018_ = _017_ | ~(state[2]);
  assign _019_ = _018_ ? _016_ : reqi[0];
  assign _000_[0] = rst ? tmp[0] : _019_;
  assign _020_ = tmp[1] & ~(state[0]);
  assign _021_ = _018_ ? _020_ : reqi[1];
  assign _000_[1] = rst ? tmp[1] : _021_;
  assign _022_ = tmp[2] & ~(state[0]);
  assign _023_ = _018_ ? _022_ : reqi[2];
  assign _000_[2] = rst ? tmp[2] : _023_;
  assign _024_ = tmp[3] & ~(state[0]);
  assign _025_ = _018_ ? _024_ : reqi[3];
  assign _000_[3] = rst ? tmp[3] : _025_;
  assign _026_ = _017_ | ~(reqi[0]);
  assign _027_ = ~(_026_ | empty);
  assign _028_ = state[2] | state[1];
  assign _029_ = _010_ | ~(tmp[0]);
  assign _030_ = ~tmp[0];
  assign _031_ = ~reqi[0];
  assign _032_ = pkto[9] & ~(pkto[8]);
  assign _033_ = _032_ ? _031_ : _030_;
  assign _034_ = ~((_029_ | _008_) & (_004_ | _033_));
  assign req[0] = _028_ ? _034_ : _027_;
  assign _035_ = _017_ | ~(reqi[1]);
  assign _036_ = ~(_035_ | empty);
  assign _037_ = _010_ | ~(tmp[1]);
  assign _038_ = ~tmp[1];
  assign _039_ = ~reqi[1];
  assign _040_ = _032_ ? _039_ : _038_;
  assign _041_ = ~((_037_ | _008_) & (_004_ | _040_));
  assign req[1] = _028_ ? _041_ : _036_;
  assign _042_ = _017_ | ~(reqi[2]);
  assign _043_ = ~(_042_ | empty);
  assign _044_ = _010_ | ~(tmp[2]);
  assign _045_ = ~tmp[2];
  assign _046_ = ~reqi[2];
  assign _047_ = _032_ ? _046_ : _045_;
  assign _048_ = ~((_044_ | _008_) & (_004_ | _047_));
  assign req[2] = _028_ ? _048_ : _043_;
  assign _049_ = _017_ | ~(reqi[3]);
  assign _050_ = ~(_049_ | empty);
  assign _051_ = _010_ | ~(tmp[3]);
  assign _052_ = ~tmp[3];
  assign _053_ = ~reqi[3];
  assign _054_ = _032_ ? _053_ : _052_;
  assign _055_ = ~((_051_ | _008_) & (_004_ | _054_));
  assign req[3] = _028_ ? _055_ : _050_;
  assign _056_ = ~ack;
  assign re = ~((_056_ | _004_) & _008_);
  always @(posedge clk)
      state[0] <= _001_;
  always @(posedge clk)
      state[1] <= _002_;
  always @(posedge clk)
      state[2] <= _003_;
  (* src = "ibsm.v:15" *)
  always @(posedge clk)
      tmp[0] <= _000_[0];
  (* src = "ibsm.v:15" *)
  always @(posedge clk)
      tmp[1] <= _000_[1];
  (* src = "ibsm.v:15" *)
  always @(posedge clk)
      tmp[2] <= _000_[2];
  (* src = "ibsm.v:15" *)
  always @(posedge clk)
      tmp[3] <= _000_[3];
endmodule

(* src = "mkreq.v:4" *)
module mkreq(clk, rst, pkto, reqi);
  (* src = "mkreq.v:10" *)
  wire [3:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  (* src = "mkreq.v:4" *)
  input clk;
  (* src = "mkreq.v:5" *)
  input [9:0] pkto;
  (* src = "mkreq.v:6" *)
  output [3:0] reqi;
  reg [3:0] reqi;
  (* src = "mkreq.v:4" *)
  input rst;
  assign _01_ = ~(pkto[1] | pkto[0]);
  assign _02_ = pkto[9] & ~(pkto[8]);
  assign _03_ = ~(_02_ & _01_);
  assign _00_[0] = ~(_03_ | rst);
  assign _04_ = pkto[1] | ~(pkto[0]);
  assign _05_ = _04_ | ~(_02_);
  assign _00_[1] = ~(_05_ | rst);
  assign _06_ = pkto[0] | ~(pkto[1]);
  assign _07_ = _06_ | ~(_02_);
  assign _00_[2] = ~(_07_ | rst);
  assign _08_ = ~(pkto[1] & pkto[0]);
  assign _09_ = _08_ | ~(_02_);
  assign _00_[3] = ~(_09_ | rst);
  (* src = "mkreq.v:10" *)
  always @(posedge clk)
      reqi[0] <= _00_[0];
  (* src = "mkreq.v:10" *)
  always @(posedge clk)
      reqi[1] <= _00_[1];
  (* src = "mkreq.v:10" *)
  always @(posedge clk)
      reqi[2] <= _00_[2];
  (* src = "mkreq.v:10" *)
  always @(posedge clk)
      reqi[3] <= _00_[3];
endmodule

(* src = "mkwe.v:4" *)
module mkwe(pkti, we);
  (* src = "mkwe.v:4" *)
  input [9:0] pkti;
  (* src = "mkwe.v:4" *)
  output we;
  assign we = pkti[9] | pkti[8];
endmodule

(* top =  1  *)
(* src = "sw.v:4" *)
module sw(clk, rst, i0, i1, i2, i3, o0, o1, o2, o3);
  (* src = "sw.v:10" *)
  wire ack0;
  (* src = "sw.v:15" *)
  wire ack00;
  (* src = "sw.v:16" *)
  wire ack01;
  (* src = "sw.v:17" *)
  wire ack02;
  (* src = "sw.v:18" *)
  wire ack03;
  (* src = "sw.v:11" *)
  wire ack1;
  (* src = "sw.v:15" *)
  wire ack10;
  (* src = "sw.v:16" *)
  wire ack11;
  (* src = "sw.v:17" *)
  wire ack12;
  (* src = "sw.v:18" *)
  wire ack13;
  (* src = "sw.v:12" *)
  wire ack2;
  (* src = "sw.v:15" *)
  wire ack20;
  (* src = "sw.v:16" *)
  wire ack21;
  (* src = "sw.v:17" *)
  wire ack22;
  (* src = "sw.v:18" *)
  wire ack23;
  (* src = "sw.v:13" *)
  wire ack3;
  (* src = "sw.v:15" *)
  wire ack30;
  (* src = "sw.v:16" *)
  wire ack31;
  (* src = "sw.v:17" *)
  wire ack32;
  (* src = "sw.v:18" *)
  wire ack33;
  (* src = "sw.v:4" *)
  input clk;
  (* src = "sw.v:6" *)
  wire [9:0] co0;
  (* src = "sw.v:6" *)
  wire [9:0] co1;
  (* src = "sw.v:6" *)
  wire [9:0] co2;
  (* src = "sw.v:6" *)
  wire [9:0] co3;
  (* src = "sw.v:10" *)
  (* unused_bits = "0" *)
  wire full0;
  (* src = "sw.v:11" *)
  (* unused_bits = "0" *)
  wire full1;
  (* src = "sw.v:12" *)
  (* unused_bits = "0" *)
  wire full2;
  (* src = "sw.v:13" *)
  (* unused_bits = "0" *)
  wire full3;
  (* src = "sw.v:4" *)
  input [9:0] i0;
  (* src = "sw.v:4" *)
  input [9:0] i1;
  (* src = "sw.v:4" *)
  input [9:0] i2;
  (* src = "sw.v:4" *)
  input [9:0] i3;
  (* src = "sw.v:4" *)
  output [9:0] o0;
  (* src = "sw.v:4" *)
  output [9:0] o1;
  (* src = "sw.v:4" *)
  output [9:0] o2;
  (* src = "sw.v:4" *)
  output [9:0] o3;
  (* src = "sw.v:7" *)
  wire [3:0] req0;
  (* src = "sw.v:7" *)
  wire [3:0] req1;
  (* src = "sw.v:7" *)
  wire [3:0] req2;
  (* src = "sw.v:7" *)
  wire [3:0] req3;
  (* src = "sw.v:4" *)
  input rst;
  (* module_not_derived = 32'd1 *)
  (* src = "sw.v:15" *)
  ackor ackor0 (
    .ack(ack0),
    .ack0(ack00),
    .ack1(ack10),
    .ack2(ack20),
    .ack3(ack30)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sw.v:16" *)
  ackor ackor1 (
    .ack(ack1),
    .ack0(ack01),
    .ack1(ack11),
    .ack2(ack21),
    .ack3(ack31)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sw.v:17" *)
  ackor ackor2 (
    .ack(ack2),
    .ack0(ack02),
    .ack1(ack12),
    .ack2(ack22),
    .ack3(ack32)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sw.v:18" *)
  ackor ackor3 (
    .ack(ack3),
    .ack0(ack03),
    .ack1(ack13),
    .ack2(ack23),
    .ack3(ack33)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sw.v:20" *)
  arb arb0 (
    .ack0(ack00),
    .ack1(ack01),
    .ack2(ack02),
    .ack3(ack03),
    .clk(clk),
    .req0(req0[0]),
    .req1(req1[0]),
    .req2(req2[0]),
    .req3(req3[0]),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sw.v:21" *)
  arb arb1 (
    .ack0(ack10),
    .ack1(ack11),
    .ack2(ack12),
    .ack3(ack13),
    .clk(clk),
    .req0(req0[1]),
    .req1(req1[1]),
    .req2(req2[1]),
    .req3(req3[1]),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sw.v:22" *)
  arb arb2 (
    .ack0(ack20),
    .ack1(ack21),
    .ack2(ack22),
    .ack3(ack23),
    .clk(clk),
    .req0(req0[2]),
    .req1(req1[2]),
    .req2(req2[2]),
    .req3(req3[2]),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sw.v:23" *)
  arb arb3 (
    .ack0(ack30),
    .ack1(ack31),
    .ack2(ack32),
    .ack3(ack33),
    .clk(clk),
    .req0(req0[3]),
    .req1(req1[3]),
    .req2(req2[3]),
    .req3(req3[3]),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sw.v:25" *)
  cb cb (
    .ack0({ ack03, ack02, ack01, ack00 }),
    .ack1({ ack13, ack12, ack11, ack10 }),
    .ack2({ ack23, ack22, ack21, ack20 }),
    .ack3({ ack33, ack32, ack31, ack30 }),
    .co0(co0),
    .co1(co1),
    .co2(co2),
    .co3(co3),
    .o0(o0),
    .o1(o1),
    .o2(o2),
    .o3(o3)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sw.v:10" *)
  ib ib0 (
    .ack(ack0),
    .clk(clk),
    .full(full0),
    .pkti(i0),
    .pkto(co0),
    .req(req0),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sw.v:11" *)
  ib ib1 (
    .ack(ack1),
    .clk(clk),
    .full(full1),
    .pkti(i1),
    .pkto(co1),
    .req(req1),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sw.v:12" *)
  ib ib2 (
    .ack(ack2),
    .clk(clk),
    .full(full2),
    .pkti(i2),
    .pkto(co2),
    .req(req2),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sw.v:13" *)
  ib ib3 (
    .ack(ack3),
    .clk(clk),
    .full(full3),
    .pkti(i3),
    .pkto(co3),
    .req(req3),
    .rst(rst)
  );
endmodule
